// Code generated by protoc-gen-trevrpc-c. DO NOT EDIT.
// clang-format off

#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include "greeter.trevrpc.h"

#define TREVRPC_C_STACK_BODY_LEN 512u
#define TREVRPC_GENERATED_RECEIVER_OPEN 1u
#define TREVRPC_GENERATED_RECEIVER_DONE 2u

#ifdef TREVRPC_GENERATED_TESTING
static size_t trevrpc_generated_allocation_budget = SIZE_MAX;
void trevrpc_hello_v1_greeter_proto_test_fail_allocation_after(size_t successful_allocations) {
    trevrpc_generated_allocation_budget = successful_allocations;
}
#endif

typedef struct trevrpc_generated_allocator_state { int failed; } trevrpc_generated_allocator_state;

static void* trevrpc_generated_alloc(void* allocator_data, size_t size) {
    trevrpc_generated_allocator_state* state = (trevrpc_generated_allocator_state*)allocator_data;
#ifdef TREVRPC_GENERATED_TESTING
    if (size != 0 && trevrpc_generated_allocation_budget == 0) { state->failed = 1; return NULL; }
    if (size != 0 && trevrpc_generated_allocation_budget != SIZE_MAX) { trevrpc_generated_allocation_budget--; }
#endif
    void* value = malloc(size);
    if (value == NULL && size != 0) { state->failed = 1; }
    return value;
}

static void trevrpc_generated_free(void* allocator_data, void* value) { (void)allocator_data; free(value); }

static ProtobufCAllocator trevrpc_generated_allocator(trevrpc_generated_allocator_state* state) {
    return (ProtobufCAllocator){.alloc = trevrpc_generated_alloc, .free = trevrpc_generated_free, .allocator_data = state};
}

static int trevrpc_generated_event_empty(uint32_t kind, int error, const void* message, const void* frame) {
    return kind == 0 && error == 0 && message == NULL && frame == NULL;
}

static int trevrpc_generated_result_empty(uint32_t kind, int error, const void* response, const void* envelope) {
    return kind == 0 && error == 0 && response == NULL && envelope == NULL;
}

int hello_v1_greeter_send_hello_v1_hello_reply(trevrpc_stream* stream, const Hello__V1__HelloReply* message) {
    if (stream == NULL || message == NULL) { return -EINVAL; }
    size_t body_len = hello__v1__hello_reply__get_packed_size(message);
    uint8_t stack_body[TREVRPC_C_STACK_BODY_LEN];
    uint8_t* body = body_len == 0 ? NULL : (body_len <= sizeof(stack_body) ? stack_body : malloc(body_len));
    if (body_len > 0 && body == NULL) { return -ENOMEM; }
    hello__v1__hello_reply__pack(message, body);
    int err = trevrpc_stream_send_message_borrowed_wait(stream, body, body_len);
    if (body != stack_body) { free(body); }
    return err;
}

int hello_v1_greeter_send_hello_v1_hello_request(trevrpc_stream* stream, const Hello__V1__HelloRequest* message) {
    if (stream == NULL || message == NULL) { return -EINVAL; }
    size_t body_len = hello__v1__hello_request__get_packed_size(message);
    uint8_t stack_body[TREVRPC_C_STACK_BODY_LEN];
    uint8_t* body = body_len == 0 ? NULL : (body_len <= sizeof(stack_body) ? stack_body : malloc(body_len));
    if (body_len > 0 && body == NULL) { return -ENOMEM; }
    hello__v1__hello_request__pack(message, body);
    int err = trevrpc_stream_send_message_borrowed_wait(stream, body, body_len);
    if (body != stack_body) { free(body); }
    return err;
}

int hello_v1_greeter_hello_request_request_receiver_init(hello_v1_greeter_hello_request_request_receiver* receiver, trevrpc_stream* stream) {
    if (receiver == NULL || stream == NULL || receiver->stream != NULL || receiver->state != 0) { return -EINVAL; }
    receiver->stream = stream;
    receiver->state = TREVRPC_GENERATED_RECEIVER_OPEN;
    return 0;
}

void hello_v1_greeter_hello_request_request_event_reset(hello_v1_greeter_hello_request_request_event* event) {
    if (event == NULL) { return; }
    if (event->message != NULL) { hello__v1__hello_request__free_unpacked(event->message, NULL); }
    trevrpc_inbound_stream_frame_release(event->frame);
    memset(event, 0, sizeof(*event));
}

void hello_v1_greeter_hello_request_request_receiver_reset(hello_v1_greeter_hello_request_request_receiver* receiver) {
    if (receiver != NULL) { memset(receiver, 0, sizeof(*receiver)); }
}

int hello_v1_greeter_recv_hello_v1_hello_request_request(hello_v1_greeter_hello_request_request_receiver* receiver, hello_v1_greeter_hello_request_request_event* event) {
    if (receiver == NULL || receiver->stream == NULL || event == NULL || !trevrpc_generated_event_empty(event->kind, event->error, event->message, event->frame)) { return -EINVAL; }
    if (receiver->state == TREVRPC_GENERATED_RECEIVER_DONE) { return 0; }
    trevrpc_inbound_stream_frame* frame = NULL;
    int err = trevrpc_stream_recv_inbound(receiver->stream, &frame);
    if (err != 0) {
        event->kind = HELLO_V1_GREETER_HELLO_REQUEST_REQUEST_EVENT_RUNTIME_ERROR;
        event->error = err;
        receiver->state = TREVRPC_GENERATED_RECEIVER_DONE;
        return 0;
    }
    if (frame == NULL) {
        event->kind = HELLO_V1_GREETER_HELLO_REQUEST_REQUEST_EVENT_END;
        receiver->state = TREVRPC_GENERATED_RECEIVER_DONE;
        return 0;
    }
    uint32_t kind = 0;
    err = trevrpc_inbound_stream_frame_get_kind(frame, &kind);
    if (err != 0) {
        trevrpc_inbound_stream_frame_release(frame);
        event->kind = HELLO_V1_GREETER_HELLO_REQUEST_REQUEST_EVENT_RUNTIME_ERROR;
        event->error = err; receiver->state = TREVRPC_GENERATED_RECEIVER_DONE; return 0;
    }
    if (kind == TREVRPC_STREAM_FRAME_KIND_MESSAGE) {
        trevrpc_bytes_view body_view = {0};
        err = trevrpc_inbound_stream_frame_get_body(frame, &body_view);
        if (err != 0) {
            trevrpc_inbound_stream_frame_release(frame);
            event->kind = HELLO_V1_GREETER_HELLO_REQUEST_REQUEST_EVENT_RUNTIME_ERROR;
            event->error = err; receiver->state = TREVRPC_GENERATED_RECEIVER_DONE; return 0;
        }
        trevrpc_generated_allocator_state allocator_state = {0};
        ProtobufCAllocator allocator = trevrpc_generated_allocator(&allocator_state);
        event->message = hello__v1__hello_request__unpack(&allocator, body_view.len, body_view.data);
        event->frame = frame;
        if (event->message == NULL) {
            event->kind = allocator_state.failed ? HELLO_V1_GREETER_HELLO_REQUEST_REQUEST_EVENT_RUNTIME_ERROR : HELLO_V1_GREETER_HELLO_REQUEST_REQUEST_EVENT_DECODE_ERROR;
            event->error = allocator_state.failed ? -ENOMEM : TREVRPC_ERR_INVALID_FRAME;
            trevrpc_stream_cancel(receiver->stream);
            receiver->state = TREVRPC_GENERATED_RECEIVER_DONE;
        } else {
            event->kind = HELLO_V1_GREETER_HELLO_REQUEST_REQUEST_EVENT_MESSAGE;
        }
        return 0;
    }
    if (kind != TREVRPC_STREAM_FRAME_KIND_STATUS) {
        trevrpc_inbound_stream_frame_release(frame);
        event->kind = HELLO_V1_GREETER_HELLO_REQUEST_REQUEST_EVENT_RUNTIME_ERROR;
        event->error = TREVRPC_ERR_INVALID_FRAME; receiver->state = TREVRPC_GENERATED_RECEIVER_DONE; return 0;
    }
    trevrpc_inbound_stream_frame* trailing = NULL;
    err = trevrpc_stream_recv_inbound(receiver->stream, &trailing);
    if (trailing != NULL) {
        trevrpc_inbound_stream_frame_release(trailing);
        trevrpc_inbound_stream_frame_release(frame);
        event->kind = HELLO_V1_GREETER_HELLO_REQUEST_REQUEST_EVENT_RUNTIME_ERROR;
        event->error = TREVRPC_ERR_INVALID_FRAME; receiver->state = TREVRPC_GENERATED_RECEIVER_DONE; return 0;
    }
    if (err != 0) {
        trevrpc_inbound_stream_frame_release(frame);
        event->kind = HELLO_V1_GREETER_HELLO_REQUEST_REQUEST_EVENT_RUNTIME_ERROR;
        event->error = (err == TREVRPC_ERR_INVALID_FRAME || err == TREVRPC_ERR_FRAME_TOO_LARGE) ? TREVRPC_ERR_INVALID_FRAME : err;
        receiver->state = TREVRPC_GENERATED_RECEIVER_DONE; return 0;
    }
    event->kind = HELLO_V1_GREETER_HELLO_REQUEST_REQUEST_EVENT_TERMINAL_STATUS;
    event->frame = frame;
    receiver->state = TREVRPC_GENERATED_RECEIVER_DONE;
    return 0;
}

int hello_v1_greeter_hello_reply_receiver_init(hello_v1_greeter_hello_reply_receiver* receiver, trevrpc_stream* stream) {
    if (receiver == NULL || stream == NULL || receiver->stream != NULL || receiver->state != 0) { return -EINVAL; }
    receiver->stream = stream;
    receiver->state = TREVRPC_GENERATED_RECEIVER_OPEN;
    return 0;
}

void hello_v1_greeter_hello_reply_event_reset(hello_v1_greeter_hello_reply_event* event) {
    if (event == NULL) { return; }
    if (event->message != NULL) { hello__v1__hello_reply__free_unpacked(event->message, NULL); }
    trevrpc_inbound_stream_frame_release(event->frame);
    memset(event, 0, sizeof(*event));
}

void hello_v1_greeter_hello_reply_receiver_reset(hello_v1_greeter_hello_reply_receiver* receiver) {
    if (receiver != NULL) { memset(receiver, 0, sizeof(*receiver)); }
}

int hello_v1_greeter_recv_hello_v1_hello_reply(hello_v1_greeter_hello_reply_receiver* receiver, hello_v1_greeter_hello_reply_event* event) {
    if (receiver == NULL || receiver->stream == NULL || event == NULL || !trevrpc_generated_event_empty(event->kind, event->error, event->message, event->frame)) { return -EINVAL; }
    if (receiver->state == TREVRPC_GENERATED_RECEIVER_DONE) { return 0; }
    trevrpc_inbound_stream_frame* frame = NULL;
    int err = trevrpc_stream_recv_inbound(receiver->stream, &frame);
    if (err != 0) {
        event->kind = HELLO_V1_GREETER_HELLO_REPLY_EVENT_RUNTIME_ERROR;
        event->error = err;
        receiver->state = TREVRPC_GENERATED_RECEIVER_DONE;
        return 0;
    }
    if (frame == NULL) {
        event->kind = HELLO_V1_GREETER_HELLO_REPLY_EVENT_MISSING_TERMINAL_STATUS;
        event->error = TREVRPC_ERR_INVALID_FRAME;
        receiver->state = TREVRPC_GENERATED_RECEIVER_DONE;
        return 0;
    }
    uint32_t kind = 0;
    err = trevrpc_inbound_stream_frame_get_kind(frame, &kind);
    if (err != 0) {
        trevrpc_inbound_stream_frame_release(frame);
        event->kind = HELLO_V1_GREETER_HELLO_REPLY_EVENT_RUNTIME_ERROR;
        event->error = err; receiver->state = TREVRPC_GENERATED_RECEIVER_DONE; return 0;
    }
    if (kind == TREVRPC_STREAM_FRAME_KIND_MESSAGE) {
        trevrpc_bytes_view body_view = {0};
        err = trevrpc_inbound_stream_frame_get_body(frame, &body_view);
        if (err != 0) {
            trevrpc_inbound_stream_frame_release(frame);
            event->kind = HELLO_V1_GREETER_HELLO_REPLY_EVENT_RUNTIME_ERROR;
            event->error = err; receiver->state = TREVRPC_GENERATED_RECEIVER_DONE; return 0;
        }
        trevrpc_generated_allocator_state allocator_state = {0};
        ProtobufCAllocator allocator = trevrpc_generated_allocator(&allocator_state);
        event->message = hello__v1__hello_reply__unpack(&allocator, body_view.len, body_view.data);
        event->frame = frame;
        if (event->message == NULL) {
            event->kind = allocator_state.failed ? HELLO_V1_GREETER_HELLO_REPLY_EVENT_RUNTIME_ERROR : HELLO_V1_GREETER_HELLO_REPLY_EVENT_DECODE_ERROR;
            event->error = allocator_state.failed ? -ENOMEM : TREVRPC_ERR_INVALID_FRAME;
            trevrpc_stream_cancel(receiver->stream);
            receiver->state = TREVRPC_GENERATED_RECEIVER_DONE;
        } else {
            event->kind = HELLO_V1_GREETER_HELLO_REPLY_EVENT_MESSAGE;
        }
        return 0;
    }
    if (kind != TREVRPC_STREAM_FRAME_KIND_STATUS) {
        trevrpc_inbound_stream_frame_release(frame);
        event->kind = HELLO_V1_GREETER_HELLO_REPLY_EVENT_RUNTIME_ERROR;
        event->error = TREVRPC_ERR_INVALID_FRAME; receiver->state = TREVRPC_GENERATED_RECEIVER_DONE; return 0;
    }
    trevrpc_inbound_stream_frame* trailing = NULL;
    err = trevrpc_stream_recv_inbound(receiver->stream, &trailing);
    if (trailing != NULL) {
        trevrpc_inbound_stream_frame_release(trailing);
        trevrpc_inbound_stream_frame_release(frame);
        event->kind = HELLO_V1_GREETER_HELLO_REPLY_EVENT_RUNTIME_ERROR;
        event->error = TREVRPC_ERR_INVALID_FRAME; receiver->state = TREVRPC_GENERATED_RECEIVER_DONE; return 0;
    }
    if (err != 0) {
        trevrpc_inbound_stream_frame_release(frame);
        event->kind = HELLO_V1_GREETER_HELLO_REPLY_EVENT_RUNTIME_ERROR;
        event->error = (err == TREVRPC_ERR_INVALID_FRAME || err == TREVRPC_ERR_FRAME_TOO_LARGE) ? TREVRPC_ERR_INVALID_FRAME : err;
        receiver->state = TREVRPC_GENERATED_RECEIVER_DONE; return 0;
    }
    event->kind = HELLO_V1_GREETER_HELLO_REPLY_EVENT_TERMINAL_STATUS;
    event->frame = frame;
    receiver->state = TREVRPC_GENERATED_RECEIVER_DONE;
    return 0;
}

void hello_v1_greeter_say_hello_result_reset(hello_v1_greeter_say_hello_result* result) {
    if (result == NULL) { return; }
    if (result->response != NULL) { hello__v1__hello_reply__free_unpacked(result->response, NULL); }
    trevrpc_inbound_response_release(result->envelope);
    memset(result, 0, sizeof(*result));
}

int hello_v1_greeter_say_hello(trevrpc_channel* channel, const Hello__V1__HelloRequest* request, hello_v1_greeter_say_hello_result* result) {
    return hello_v1_greeter_say_hello_with_options(channel, request, NULL, result);
}

int hello_v1_greeter_say_hello_with_options(trevrpc_channel* channel, const Hello__V1__HelloRequest* request, const trevrpc_call_options_v1* options, hello_v1_greeter_say_hello_result* result) {
    if (channel == NULL || request == NULL || result == NULL || !trevrpc_generated_result_empty(result->kind, result->error, result->response, result->envelope)) { return -EINVAL; }
    size_t body_len = hello__v1__hello_request__get_packed_size(request);
    uint8_t stack_body[TREVRPC_C_STACK_BODY_LEN];
    uint8_t* body = body_len == 0 ? NULL : (body_len <= sizeof(stack_body) ? stack_body : malloc(body_len));
    if (body_len > 0 && body == NULL) { result->kind = HELLO_V1_GREETER_SAY_HELLO_RESULT_RUNTIME_ERROR; result->error = -ENOMEM; return 0; }
    hello__v1__hello_request__pack(request, body);
    trevrpc_request rpc_request = {.service = "hello.v1.Greeter", .service_len = sizeof("hello.v1.Greeter") - 1, .method = "SayHello", .method_len = sizeof("SayHello") - 1, .body = body, .body_len = body_len, .kind = TREVRPC_RPC_KIND_UNARY, .version = TREVRPC_WIRE_VERSION};
    int err = trevrpc_channel_call_request_inbound_v1(channel, &rpc_request, options, &result->envelope);
    if (body != stack_body) { free(body); }
    if (err != 0) { result->kind = HELLO_V1_GREETER_SAY_HELLO_RESULT_RUNTIME_ERROR; result->error = err; return 0; }
    uint32_t status = TREVRPC_STATUS_OK;
    err = trevrpc_inbound_response_get_status(result->envelope, &status);
    if (err != 0) { result->kind = HELLO_V1_GREETER_SAY_HELLO_RESULT_RUNTIME_ERROR; result->error = err; return 0; }
    if (status != TREVRPC_STATUS_OK) { result->kind = HELLO_V1_GREETER_SAY_HELLO_RESULT_RPC_STATUS; return 0; }
    trevrpc_bytes_view body_view = {0};
    err = trevrpc_inbound_response_get_body(result->envelope, &body_view);
    if (err != 0) { result->kind = HELLO_V1_GREETER_SAY_HELLO_RESULT_RUNTIME_ERROR; result->error = err; return 0; }
    trevrpc_generated_allocator_state allocator_state = {0};
    ProtobufCAllocator allocator = trevrpc_generated_allocator(&allocator_state);
    result->response = hello__v1__hello_reply__unpack(&allocator, body_view.len, body_view.data);
    if (result->response == NULL) { result->kind = allocator_state.failed ? HELLO_V1_GREETER_SAY_HELLO_RESULT_RUNTIME_ERROR : HELLO_V1_GREETER_SAY_HELLO_RESULT_DECODE_ERROR;
        result->error = allocator_state.failed ? -ENOMEM : TREVRPC_ERR_INVALID_FRAME; return 0; }
    result->kind = HELLO_V1_GREETER_SAY_HELLO_RESULT_SUCCESS;
    return 0;
}

typedef struct hello_v1_greeter_say_hello_respond_context { trevrpc_call* call; int attempted; int submitted; int error; } hello_v1_greeter_say_hello_respond_context;

static int hello_v1_greeter_say_hello_respond(void* context_value, const hello_v1_greeter_say_hello_response_view* response) {
    hello_v1_greeter_say_hello_respond_context* context = (hello_v1_greeter_say_hello_respond_context*)context_value;
    if (context == NULL || context->call == NULL || response == NULL) { return -EINVAL; }
    if (context->attempted) { return -EALREADY; }
    if ((response->status == TREVRPC_STATUS_OK && response->message == NULL) || (response->status != TREVRPC_STATUS_OK && response->message != NULL) || (response->status_message == NULL && response->status_message_len > 0)) { return -EINVAL; }
    context->attempted = 1;
    uint8_t stack_body[TREVRPC_C_STACK_BODY_LEN];
    uint8_t* body = NULL;
    size_t body_len = 0;
    if (response->message != NULL) {
        body_len = hello__v1__hello_reply__get_packed_size(response->message);
        body = body_len == 0 ? NULL : (body_len <= sizeof(stack_body) ? stack_body : malloc(body_len));
        if (body_len > 0 && body == NULL) { context->error = -ENOMEM; return context->error; }
        hello__v1__hello_reply__pack(response->message, body);
    }
    trevrpc_response_view_v1 view;
    int err = trevrpc_response_view_v1_init(&view, sizeof(view));
    if (err == 0) {
        view.status = response->status; view.message = response->status_message; view.message_len = response->status_message_len; view.body = body; view.body_len = body_len; view.metadata = response->metadata;
        err = trevrpc_call_respond_borrowed_v1(context->call, &view);
    }
    if (body != stack_body) { free(body); }
    context->error = err;
    context->submitted = err == 0;
    return err;
}

static int hello_v1_greeter_say_hello_callback(void* user_data, trevrpc_call* call) {
    const hello_v1_greeter_server* implementation = (const hello_v1_greeter_server*)user_data;
    const trevrpc_call_context* context = trevrpc_call_get_context(call);
    const trevrpc_request* request = trevrpc_call_request(call);
    Hello__V1__HelloRequest* decoded = request == NULL ? NULL : hello__v1__hello_request__unpack(NULL, request->body_len, request->body);
    if (decoded == NULL) { return TREVRPC_ERR_INVALID_FRAME; }
    hello_v1_greeter_say_hello_respond_context respond_context = {.call = call};
    int err = implementation->say_hello(implementation->user_data, context, decoded, hello_v1_greeter_say_hello_respond, &respond_context);
    hello__v1__hello_request__free_unpacked(decoded, NULL);
    if (respond_context.submitted) { return 0; }
    if (respond_context.attempted && respond_context.error != 0) { return respond_context.error; }
    return err != 0 ? err : TREVRPC_ERR_HANDLER_FAILED;
}

int hello_v1_greeter_lots_of_replies(trevrpc_channel* channel, const Hello__V1__HelloRequest* request, trevrpc_stream** stream) { return hello_v1_greeter_lots_of_replies_with_options(channel, request, NULL, stream); }

int hello_v1_greeter_lots_of_replies_with_options(trevrpc_channel* channel, const Hello__V1__HelloRequest* request, const trevrpc_call_options_v1* options, trevrpc_stream** stream) {
    if (channel == NULL || request == NULL || stream == NULL) { return -EINVAL; }
    size_t body_len = hello__v1__hello_request__get_packed_size(request);
    uint8_t stack_body[TREVRPC_C_STACK_BODY_LEN];
    uint8_t* body = body_len == 0 ? NULL : (body_len <= sizeof(stack_body) ? stack_body : malloc(body_len));
    if (body_len > 0 && body == NULL) { return -ENOMEM; }
    hello__v1__hello_request__pack(request, body);
    trevrpc_request rpc_request = {.service = "hello.v1.Greeter", .service_len = sizeof("hello.v1.Greeter") - 1, .method = "LotsOfReplies", .method_len = sizeof("LotsOfReplies") - 1, .body = body, .body_len = body_len, .kind = TREVRPC_RPC_KIND_SERVER_STREAMING, .version = TREVRPC_WIRE_VERSION};
    int err = trevrpc_channel_start_stream_request_v1(channel, &rpc_request, options, stream);
    if (body != stack_body) { free(body); }
    if (err == 0) { err = trevrpc_stream_finish_send(*stream); }
    if (err != 0 && *stream != NULL) { trevrpc_stream_close(*stream); *stream = NULL; }
    return err;
}

static int hello_v1_greeter_lots_of_replies_callback(void* user_data, trevrpc_call* call) {
    const hello_v1_greeter_server* implementation = (const hello_v1_greeter_server*)user_data;
    const trevrpc_call_context* context = trevrpc_call_get_context(call);
    trevrpc_stream* stream = trevrpc_call_stream(call);
    const trevrpc_request* request = trevrpc_call_request(call);
    Hello__V1__HelloRequest* decoded = request == NULL ? NULL : hello__v1__hello_request__unpack(NULL, request->body_len, request->body);
    if (decoded == NULL) { return TREVRPC_ERR_INVALID_FRAME; }
    int err = implementation->lots_of_replies(implementation->user_data, context, decoded, stream);
    hello__v1__hello_request__free_unpacked(decoded, NULL);
    if (err != 0) { return err; }
    trevrpc_status_view_v1 status;
    err = trevrpc_status_view_v1_init(&status, sizeof(status));
    return err == 0 ? trevrpc_call_finish_stream_borrowed_v1(call, &status) : err;
}

int hello_v1_greeter_lots_of_greetings_start(trevrpc_channel* channel, trevrpc_stream** stream) { return hello_v1_greeter_lots_of_greetings_start_with_options(channel, NULL, stream); }

int hello_v1_greeter_lots_of_greetings_start_with_options(trevrpc_channel* channel, const trevrpc_call_options_v1* options, trevrpc_stream** stream) {
    if (channel == NULL || stream == NULL) { return -EINVAL; }
    trevrpc_request request = {.service = "hello.v1.Greeter", .service_len = sizeof("hello.v1.Greeter") - 1, .method = "LotsOfGreetings", .method_len = sizeof("LotsOfGreetings") - 1, .kind = TREVRPC_RPC_KIND_CLIENT_STREAMING, .version = TREVRPC_WIRE_VERSION};
    return trevrpc_channel_start_stream_request_v1(channel, &request, options, stream);
}

typedef struct hello_v1_greeter_lots_of_greetings_respond_context { trevrpc_call* call; int attempted; int submitted; int error; } hello_v1_greeter_lots_of_greetings_respond_context;

static int hello_v1_greeter_lots_of_greetings_respond(void* context_value, const hello_v1_greeter_lots_of_greetings_response_view* response) {
    hello_v1_greeter_lots_of_greetings_respond_context* context = (hello_v1_greeter_lots_of_greetings_respond_context*)context_value;
    if (context == NULL || context->call == NULL || response == NULL) { return -EINVAL; }
    if (context->attempted) { return -EALREADY; }
    if ((response->status == TREVRPC_STATUS_OK && response->message == NULL) || (response->status != TREVRPC_STATUS_OK && response->message != NULL) || (response->status_message == NULL && response->status_message_len > 0)) { return -EINVAL; }
    context->attempted = 1;
    uint8_t stack_body[TREVRPC_C_STACK_BODY_LEN];
    uint8_t* body = NULL;
    size_t body_len = 0;
    if (response->message != NULL) {
        body_len = hello__v1__hello_reply__get_packed_size(response->message);
        body = body_len == 0 ? NULL : (body_len <= sizeof(stack_body) ? stack_body : malloc(body_len));
        if (body_len > 0 && body == NULL) { context->error = -ENOMEM; return context->error; }
        hello__v1__hello_reply__pack(response->message, body);
    }
    trevrpc_stream* stream = trevrpc_call_stream(context->call);
    int err = stream == NULL ? -EINVAL : 0;
    if (err == 0 && response->message != NULL) {
        err = trevrpc_stream_send_message_borrowed_wait(stream, body, body_len);
    }
    trevrpc_status_view_v1 status;
    if (err == 0) { err = trevrpc_status_view_v1_init(&status, sizeof(status)); }
    if (err == 0) {
        status.status = response->status; status.message = response->status_message; status.message_len = response->status_message_len; status.metadata = response->metadata;
        err = trevrpc_call_finish_stream_borrowed_v1(context->call, &status);
    }
    if (body != stack_body) { free(body); }
    context->error = err;
    context->submitted = err == 0;
    return err;
}

static int hello_v1_greeter_lots_of_greetings_callback(void* user_data, trevrpc_call* call) {
    const hello_v1_greeter_server* implementation = (const hello_v1_greeter_server*)user_data;
    const trevrpc_call_context* context = trevrpc_call_get_context(call);
    trevrpc_stream* stream = trevrpc_call_stream(call);
    hello_v1_greeter_lots_of_greetings_respond_context respond_context = {.call = call};
    int err = implementation->lots_of_greetings(implementation->user_data, context, stream, hello_v1_greeter_lots_of_greetings_respond, &respond_context);
    if (respond_context.submitted) { return 0; }
    if (respond_context.attempted && respond_context.error != 0) { return respond_context.error; }
    return err != 0 ? err : TREVRPC_ERR_HANDLER_FAILED;
}

int hello_v1_greeter_bidi_hello_start(trevrpc_channel* channel, trevrpc_stream** stream) { return hello_v1_greeter_bidi_hello_start_with_options(channel, NULL, stream); }

int hello_v1_greeter_bidi_hello_start_with_options(trevrpc_channel* channel, const trevrpc_call_options_v1* options, trevrpc_stream** stream) {
    if (channel == NULL || stream == NULL) { return -EINVAL; }
    trevrpc_request request = {.service = "hello.v1.Greeter", .service_len = sizeof("hello.v1.Greeter") - 1, .method = "BidiHello", .method_len = sizeof("BidiHello") - 1, .kind = TREVRPC_RPC_KIND_BIDIRECTIONAL_STREAMING, .version = TREVRPC_WIRE_VERSION};
    return trevrpc_channel_start_stream_request_v1(channel, &request, options, stream);
}

static int hello_v1_greeter_bidi_hello_callback(void* user_data, trevrpc_call* call) {
    const hello_v1_greeter_server* implementation = (const hello_v1_greeter_server*)user_data;
    const trevrpc_call_context* context = trevrpc_call_get_context(call);
    trevrpc_stream* stream = trevrpc_call_stream(call);
    int err = implementation->bidi_hello(implementation->user_data, context, stream);
    if (err != 0) { return err; }
    trevrpc_status_view_v1 status;
    err = trevrpc_status_view_v1_init(&status, sizeof(status));
    return err == 0 ? trevrpc_call_finish_stream_borrowed_v1(call, &status) : err;
}

int hello_v1_greeter_register(trevrpc_server* server, const hello_v1_greeter_server* implementation) {
    if (server == NULL || implementation == NULL) { return -EINVAL; }
    if (implementation->say_hello == NULL) { return -EINVAL; }
    if (implementation->lots_of_replies == NULL) { return -EINVAL; }
    if (implementation->lots_of_greetings == NULL) { return -EINVAL; }
    if (implementation->bidi_hello == NULL) { return -EINVAL; }
    int err_say_hello = trevrpc_server_register_call(server, "hello.v1.Greeter", "SayHello", TREVRPC_RPC_KIND_UNARY, hello_v1_greeter_say_hello_callback, (void*)implementation);
    if (err_say_hello != 0) { return err_say_hello; }
    int err_lots_of_replies = trevrpc_server_register_call(server, "hello.v1.Greeter", "LotsOfReplies", TREVRPC_RPC_KIND_SERVER_STREAMING, hello_v1_greeter_lots_of_replies_callback, (void*)implementation);
    if (err_lots_of_replies != 0) { return err_lots_of_replies; }
    int err_lots_of_greetings = trevrpc_server_register_call(server, "hello.v1.Greeter", "LotsOfGreetings", TREVRPC_RPC_KIND_CLIENT_STREAMING, hello_v1_greeter_lots_of_greetings_callback, (void*)implementation);
    if (err_lots_of_greetings != 0) { return err_lots_of_greetings; }
    int err_bidi_hello = trevrpc_server_register_call(server, "hello.v1.Greeter", "BidiHello", TREVRPC_RPC_KIND_BIDIRECTIONAL_STREAMING, hello_v1_greeter_bidi_hello_callback, (void*)implementation);
    if (err_bidi_hello != 0) { return err_bidi_hello; }
    return 0;
}
