// Code generated by protoc-gen-trevrpc-c. DO NOT EDIT.
// clang-format off

#include <errno.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include "greeter.trevrpc.h"

#define TREVRPC_GENERATED_STACK_BODY_LEN 512u

#ifdef TREVRPC_GENERATED_TESTING
static size_t trevrpc_generated_allocation_budget = SIZE_MAX;
#endif

typedef struct trevrpc_generated_allocator_state { int failed; } trevrpc_generated_allocator_state;

static void* trevrpc_generated_alloc(void* allocator_data, size_t size) {
    trevrpc_generated_allocator_state* state = (trevrpc_generated_allocator_state*)allocator_data;
#ifdef TREVRPC_GENERATED_TESTING
    if (size != 0 && trevrpc_generated_allocation_budget == 0) { state->failed = 1; return NULL; }
    if (size != 0 && trevrpc_generated_allocation_budget != SIZE_MAX) { trevrpc_generated_allocation_budget--; }
#endif
    void* value = malloc(size);
    if (value == NULL && size != 0) { state->failed = 1; }
    return value;
}

static void trevrpc_generated_free(void* allocator_data, void* value) { (void)allocator_data; free(value); }

static ProtobufCAllocator trevrpc_generated_allocator(trevrpc_generated_allocator_state* state) {
    return (ProtobufCAllocator){.alloc = trevrpc_generated_alloc, .free = trevrpc_generated_free, .allocator_data = state};
}
#ifdef TREVRPC_GENERATED_TESTING
void trevrpc_hello_v1_greeter_proto_test_fail_allocation_after(size_t successful_allocations) { trevrpc_generated_allocation_budget = successful_allocations; }
#endif

int hello_v1_greeter_say_hello_call_config_init(trevrpc_rpc_call_config_v1* config, size_t struct_size) {
    int err = trevrpc_rpc_call_config_v1_init(config, struct_size);
    if (err != 0) { return err; }
    config->kind = TREVRPC_RPC_KIND_UNARY; config->service = "hello.v1.Greeter"; config->service_len = sizeof("hello.v1.Greeter") - 1;
    config->method = "SayHello"; config->method_len = sizeof("SayHello") - 1; return 0;
}

int hello_v1_greeter_say_hello_open(trevrpc_rpc_runtime* runtime, trevrpc_rpc_endpoint_v1 endpoint, const Hello__V1__HelloRequest* initial_or_null, uint64_t operation_id, trevrpc_rpc_call_v1* out_call, trevrpc_rpc_stream_v1* out_stream) {
    if (runtime == NULL || operation_id == TREVRPC_RPC_OPERATION_ID_NONE || out_call == NULL || out_stream == NULL) { return -EINVAL; }
    trevrpc_rpc_call_config_v1 config; int err = hello_v1_greeter_say_hello_call_config_init(&config, sizeof(config));
    if (err != 0) { return err; }
    uint8_t stack_body[TREVRPC_GENERATED_STACK_BODY_LEN]; uint8_t* body = NULL; size_t body_len = 0;
    if (initial_or_null != NULL) {
        body_len = hello__v1__hello_request__get_packed_size(initial_or_null);
        body = body_len == 0 ? stack_body : (body_len <= sizeof(stack_body) ? stack_body : malloc(body_len));
        if (body_len > 0 && body == NULL) { return -ENOMEM; }
        hello__v1__hello_request__pack(initial_or_null, body); config.initial_message = body; config.initial_message_len = body_len;
    }
    err = trevrpc_rpc_call_open_v1(runtime, endpoint, &config, operation_id, out_call, out_stream);
    if (initial_or_null != NULL) { if (body != stack_body) { free(body); } }
    return err;
}

int hello_v1_greeter_say_hello_respond(trevrpc_rpc_runtime* runtime, trevrpc_rpc_call_v1 call, const Hello__V1__HelloReply* message, const trevrpc_rpc_status_v1* status, uint64_t operation_id) {
    if (runtime == NULL || status == NULL || operation_id == TREVRPC_RPC_OPERATION_ID_NONE) { return -EINVAL; }
    uint8_t stack_body[TREVRPC_GENERATED_STACK_BODY_LEN]; uint8_t* body = NULL; size_t body_len = 0;
    if (message != NULL) {
        body_len = hello__v1__hello_reply__get_packed_size(message);
        body = body_len == 0 ? stack_body : (body_len <= sizeof(stack_body) ? stack_body : malloc(body_len));
        if (body_len > 0 && body == NULL) { return -ENOMEM; }
        hello__v1__hello_reply__pack(message, body);
    }
    int err = trevrpc_rpc_call_respond_copy_v1(runtime, call, operation_id, status, body, body_len);
    if (body != stack_body) { free(body); }
    return err;
}

int hello_v1_greeter_say_hello_decode_request_receive(const trevrpc_rpc_receive* receive, Hello__V1__HelloRequest** out_message) {
    if (receive == NULL || out_message == NULL) { return -EINVAL; }
    trevrpc_rpc_receive_info_v1 info; int err = trevrpc_rpc_receive_info_v1_init(&info, sizeof(info));
    if (err == 0) { err = trevrpc_rpc_receive_get_info_v1(receive, &info); }
    if (err != 0) { return err; }
    if (info.kind != TREVRPC_RPC_RECEIVE_INITIAL_MESSAGE) { return -EPROTO; }
    if (info.data_len > SIZE_MAX) { return -EOVERFLOW; }
    trevrpc_generated_allocator_state allocator_state = {0};
    ProtobufCAllocator allocator = trevrpc_generated_allocator(&allocator_state);
    Hello__V1__HelloRequest* message = hello__v1__hello_request__unpack(&allocator, (size_t)info.data_len, info.data);
    if (message == NULL) { return allocator_state.failed ? -ENOMEM : -EPROTO; }
    *out_message = message;
    return 0;
}

int hello_v1_greeter_say_hello_decode_response_receive(const trevrpc_rpc_receive* receive, Hello__V1__HelloReply** out_message) {
    if (receive == NULL || out_message == NULL) { return -EINVAL; }
    trevrpc_rpc_receive_info_v1 info; int err = trevrpc_rpc_receive_info_v1_init(&info, sizeof(info));
    if (err == 0) { err = trevrpc_rpc_receive_get_info_v1(receive, &info); }
    if (err != 0) { return err; }
    if (info.kind != TREVRPC_RPC_RECEIVE_MESSAGE) { return -EPROTO; }
    if (info.data_len > SIZE_MAX) { return -EOVERFLOW; }
    trevrpc_generated_allocator_state allocator_state = {0};
    ProtobufCAllocator allocator = trevrpc_generated_allocator(&allocator_state);
    Hello__V1__HelloReply* message = hello__v1__hello_reply__unpack(&allocator, (size_t)info.data_len, info.data);
    if (message == NULL) { return allocator_state.failed ? -ENOMEM : -EPROTO; }
    *out_message = message;
    return 0;
}

int hello_v1_greeter_say_hello_matches_incoming(const trevrpc_rpc_event_info_v1* info) {
    if (info == NULL || info->kind != TREVRPC_RPC_EVENT_CALL_INCOMING || info->rpc_kind != TREVRPC_RPC_KIND_UNARY) { return 0; }
    return info->service != NULL && info->method != NULL && info->service_len == sizeof("hello.v1.Greeter") - 1 && memcmp(info->service, "hello.v1.Greeter", sizeof("hello.v1.Greeter") - 1) == 0 && info->method_len == sizeof("SayHello") - 1 && memcmp(info->method, "SayHello", sizeof("SayHello") - 1) == 0;
}

int hello_v1_greeter_say_hello_take_incoming(trevrpc_rpc_event* event, trevrpc_rpc_call_v1* out_call, trevrpc_rpc_stream_v1* out_stream, trevrpc_rpc_receive** out_initial) {
    if (event == NULL || out_call == NULL || out_stream == NULL || out_initial == NULL) { return -EINVAL; }
    trevrpc_rpc_event_info_v1 info; int err = trevrpc_rpc_event_info_v1_init(&info, sizeof(info));
    if (err == 0) { err = trevrpc_rpc_event_get_info_v1(event, &info); }
    if (err == 0 && !hello_v1_greeter_say_hello_matches_incoming(&info)) { err = -EPROTO; }
    if (err != 0) { return err; }
    trevrpc_rpc_call_v1 call = {0}; trevrpc_rpc_stream_v1 stream = {0}; trevrpc_rpc_receive* initial = NULL;
    err = trevrpc_rpc_event_take_incoming_call(event, &call, &stream, &initial);
    if (err != 0) { return err; }
    *out_call = call; *out_stream = stream; *out_initial = initial;
    return 0;
}

int hello_v1_greeter_say_hello_accept(trevrpc_rpc_runtime* runtime, trevrpc_rpc_call_v1 call, uint64_t operation_id) {
    if (runtime == NULL || operation_id == TREVRPC_RPC_OPERATION_ID_NONE) { return -EINVAL; }
    return trevrpc_rpc_call_accept(runtime, call, operation_id);
}

int hello_v1_greeter_lots_of_replies_call_config_init(trevrpc_rpc_call_config_v1* config, size_t struct_size) {
    int err = trevrpc_rpc_call_config_v1_init(config, struct_size);
    if (err != 0) { return err; }
    config->kind = TREVRPC_RPC_KIND_SERVER_STREAMING; config->service = "hello.v1.Greeter"; config->service_len = sizeof("hello.v1.Greeter") - 1;
    config->method = "LotsOfReplies"; config->method_len = sizeof("LotsOfReplies") - 1; return 0;
}

int hello_v1_greeter_lots_of_replies_open(trevrpc_rpc_runtime* runtime, trevrpc_rpc_endpoint_v1 endpoint, const Hello__V1__HelloRequest* initial_or_null, uint64_t operation_id, trevrpc_rpc_call_v1* out_call, trevrpc_rpc_stream_v1* out_stream) {
    if (runtime == NULL || operation_id == TREVRPC_RPC_OPERATION_ID_NONE || out_call == NULL || out_stream == NULL) { return -EINVAL; }
    trevrpc_rpc_call_config_v1 config; int err = hello_v1_greeter_lots_of_replies_call_config_init(&config, sizeof(config));
    if (err != 0) { return err; }
    uint8_t stack_body[TREVRPC_GENERATED_STACK_BODY_LEN]; uint8_t* body = NULL; size_t body_len = 0;
    if (initial_or_null != NULL) {
        body_len = hello__v1__hello_request__get_packed_size(initial_or_null);
        body = body_len == 0 ? stack_body : (body_len <= sizeof(stack_body) ? stack_body : malloc(body_len));
        if (body_len > 0 && body == NULL) { return -ENOMEM; }
        hello__v1__hello_request__pack(initial_or_null, body); config.initial_message = body; config.initial_message_len = body_len;
    }
    err = trevrpc_rpc_call_open_v1(runtime, endpoint, &config, operation_id, out_call, out_stream);
    if (initial_or_null != NULL) { if (body != stack_body) { free(body); } }
    return err;
}

int hello_v1_greeter_lots_of_replies_send(trevrpc_rpc_runtime* runtime, trevrpc_rpc_stream_v1 stream, const Hello__V1__HelloReply* message, uint64_t operation_id) {
    if (runtime == NULL || message == NULL || operation_id == TREVRPC_RPC_OPERATION_ID_NONE) { return -EINVAL; }
    size_t body_len = hello__v1__hello_reply__get_packed_size(message);
    uint8_t stack_body[TREVRPC_GENERATED_STACK_BODY_LEN];
    uint8_t* body = body_len == 0 ? stack_body : (body_len <= sizeof(stack_body) ? stack_body : malloc(body_len));
    if (body_len > 0 && body == NULL) { return -ENOMEM; }
    hello__v1__hello_reply__pack(message, body);
    int err = trevrpc_rpc_stream_send_copy_v1(runtime, stream, operation_id, body, body_len, TREVRPC_RPC_SEND_FLAG_NONE);
    if (body != stack_body) { free(body); }
    return err;
}

int hello_v1_greeter_lots_of_replies_finish(trevrpc_rpc_runtime* runtime, trevrpc_rpc_call_v1 call, uint64_t operation_id, const trevrpc_rpc_status_v1* status) {
    if (runtime == NULL || status == NULL || operation_id == TREVRPC_RPC_OPERATION_ID_NONE) { return -EINVAL; }
    return trevrpc_rpc_call_finish_v1(runtime, call, operation_id, status);
}

int hello_v1_greeter_lots_of_replies_decode_request_receive(const trevrpc_rpc_receive* receive, Hello__V1__HelloRequest** out_message) {
    if (receive == NULL || out_message == NULL) { return -EINVAL; }
    trevrpc_rpc_receive_info_v1 info; int err = trevrpc_rpc_receive_info_v1_init(&info, sizeof(info));
    if (err == 0) { err = trevrpc_rpc_receive_get_info_v1(receive, &info); }
    if (err != 0) { return err; }
    if (info.kind != TREVRPC_RPC_RECEIVE_INITIAL_MESSAGE) { return -EPROTO; }
    if (info.data_len > SIZE_MAX) { return -EOVERFLOW; }
    trevrpc_generated_allocator_state allocator_state = {0};
    ProtobufCAllocator allocator = trevrpc_generated_allocator(&allocator_state);
    Hello__V1__HelloRequest* message = hello__v1__hello_request__unpack(&allocator, (size_t)info.data_len, info.data);
    if (message == NULL) { return allocator_state.failed ? -ENOMEM : -EPROTO; }
    *out_message = message;
    return 0;
}

int hello_v1_greeter_lots_of_replies_decode_response_receive(const trevrpc_rpc_receive* receive, Hello__V1__HelloReply** out_message) {
    if (receive == NULL || out_message == NULL) { return -EINVAL; }
    trevrpc_rpc_receive_info_v1 info; int err = trevrpc_rpc_receive_info_v1_init(&info, sizeof(info));
    if (err == 0) { err = trevrpc_rpc_receive_get_info_v1(receive, &info); }
    if (err != 0) { return err; }
    if (info.kind != TREVRPC_RPC_RECEIVE_MESSAGE) { return -EPROTO; }
    if (info.data_len > SIZE_MAX) { return -EOVERFLOW; }
    trevrpc_generated_allocator_state allocator_state = {0};
    ProtobufCAllocator allocator = trevrpc_generated_allocator(&allocator_state);
    Hello__V1__HelloReply* message = hello__v1__hello_reply__unpack(&allocator, (size_t)info.data_len, info.data);
    if (message == NULL) { return allocator_state.failed ? -ENOMEM : -EPROTO; }
    *out_message = message;
    return 0;
}

int hello_v1_greeter_lots_of_replies_matches_incoming(const trevrpc_rpc_event_info_v1* info) {
    if (info == NULL || info->kind != TREVRPC_RPC_EVENT_CALL_INCOMING || info->rpc_kind != TREVRPC_RPC_KIND_SERVER_STREAMING) { return 0; }
    return info->service != NULL && info->method != NULL && info->service_len == sizeof("hello.v1.Greeter") - 1 && memcmp(info->service, "hello.v1.Greeter", sizeof("hello.v1.Greeter") - 1) == 0 && info->method_len == sizeof("LotsOfReplies") - 1 && memcmp(info->method, "LotsOfReplies", sizeof("LotsOfReplies") - 1) == 0;
}

int hello_v1_greeter_lots_of_replies_take_incoming(trevrpc_rpc_event* event, trevrpc_rpc_call_v1* out_call, trevrpc_rpc_stream_v1* out_stream, trevrpc_rpc_receive** out_initial) {
    if (event == NULL || out_call == NULL || out_stream == NULL || out_initial == NULL) { return -EINVAL; }
    trevrpc_rpc_event_info_v1 info; int err = trevrpc_rpc_event_info_v1_init(&info, sizeof(info));
    if (err == 0) { err = trevrpc_rpc_event_get_info_v1(event, &info); }
    if (err == 0 && !hello_v1_greeter_lots_of_replies_matches_incoming(&info)) { err = -EPROTO; }
    if (err != 0) { return err; }
    trevrpc_rpc_call_v1 call = {0}; trevrpc_rpc_stream_v1 stream = {0}; trevrpc_rpc_receive* initial = NULL;
    err = trevrpc_rpc_event_take_incoming_call(event, &call, &stream, &initial);
    if (err != 0) { return err; }
    *out_call = call; *out_stream = stream; *out_initial = initial;
    return 0;
}

int hello_v1_greeter_lots_of_replies_accept(trevrpc_rpc_runtime* runtime, trevrpc_rpc_call_v1 call, uint64_t operation_id) {
    if (runtime == NULL || operation_id == TREVRPC_RPC_OPERATION_ID_NONE) { return -EINVAL; }
    return trevrpc_rpc_call_accept(runtime, call, operation_id);
}

int hello_v1_greeter_lots_of_greetings_call_config_init(trevrpc_rpc_call_config_v1* config, size_t struct_size) {
    int err = trevrpc_rpc_call_config_v1_init(config, struct_size);
    if (err != 0) { return err; }
    config->kind = TREVRPC_RPC_KIND_CLIENT_STREAMING; config->service = "hello.v1.Greeter"; config->service_len = sizeof("hello.v1.Greeter") - 1;
    config->method = "LotsOfGreetings"; config->method_len = sizeof("LotsOfGreetings") - 1; return 0;
}

int hello_v1_greeter_lots_of_greetings_open(trevrpc_rpc_runtime* runtime, trevrpc_rpc_endpoint_v1 endpoint, const Hello__V1__HelloRequest* initial_or_null, uint64_t operation_id, trevrpc_rpc_call_v1* out_call, trevrpc_rpc_stream_v1* out_stream) {
    if (runtime == NULL || operation_id == TREVRPC_RPC_OPERATION_ID_NONE || out_call == NULL || out_stream == NULL) { return -EINVAL; }
    trevrpc_rpc_call_config_v1 config; int err = hello_v1_greeter_lots_of_greetings_call_config_init(&config, sizeof(config));
    if (err != 0) { return err; }
    uint8_t stack_body[TREVRPC_GENERATED_STACK_BODY_LEN]; uint8_t* body = NULL; size_t body_len = 0;
    if (initial_or_null != NULL) {
        body_len = hello__v1__hello_request__get_packed_size(initial_or_null);
        body = body_len == 0 ? stack_body : (body_len <= sizeof(stack_body) ? stack_body : malloc(body_len));
        if (body_len > 0 && body == NULL) { return -ENOMEM; }
        hello__v1__hello_request__pack(initial_or_null, body); config.initial_message = body; config.initial_message_len = body_len;
    }
    err = trevrpc_rpc_call_open_v1(runtime, endpoint, &config, operation_id, out_call, out_stream);
    if (initial_or_null != NULL) { if (body != stack_body) { free(body); } }
    return err;
}

int hello_v1_greeter_lots_of_greetings_send(trevrpc_rpc_runtime* runtime, trevrpc_rpc_stream_v1 stream, const Hello__V1__HelloRequest* message, uint64_t operation_id) {
    if (runtime == NULL || message == NULL || operation_id == TREVRPC_RPC_OPERATION_ID_NONE) { return -EINVAL; }
    size_t body_len = hello__v1__hello_request__get_packed_size(message);
    uint8_t stack_body[TREVRPC_GENERATED_STACK_BODY_LEN];
    uint8_t* body = body_len == 0 ? stack_body : (body_len <= sizeof(stack_body) ? stack_body : malloc(body_len));
    if (body_len > 0 && body == NULL) { return -ENOMEM; }
    hello__v1__hello_request__pack(message, body);
    int err = trevrpc_rpc_stream_send_copy_v1(runtime, stream, operation_id, body, body_len, TREVRPC_RPC_SEND_FLAG_NONE);
    if (body != stack_body) { free(body); }
    return err;
}

int hello_v1_greeter_lots_of_greetings_finish_send(trevrpc_rpc_runtime* runtime, trevrpc_rpc_stream_v1 stream, uint64_t operation_id) {
    if (runtime == NULL || operation_id == TREVRPC_RPC_OPERATION_ID_NONE) { return -EINVAL; }
    return trevrpc_rpc_stream_finish_send(runtime, stream, operation_id);
}

int hello_v1_greeter_lots_of_greetings_respond(trevrpc_rpc_runtime* runtime, trevrpc_rpc_call_v1 call, const Hello__V1__HelloReply* message, const trevrpc_rpc_status_v1* status, uint64_t operation_id) {
    if (runtime == NULL || status == NULL || operation_id == TREVRPC_RPC_OPERATION_ID_NONE) { return -EINVAL; }
    uint8_t stack_body[TREVRPC_GENERATED_STACK_BODY_LEN]; uint8_t* body = NULL; size_t body_len = 0;
    if (message != NULL) {
        body_len = hello__v1__hello_reply__get_packed_size(message);
        body = body_len == 0 ? stack_body : (body_len <= sizeof(stack_body) ? stack_body : malloc(body_len));
        if (body_len > 0 && body == NULL) { return -ENOMEM; }
        hello__v1__hello_reply__pack(message, body);
    }
    int err = trevrpc_rpc_call_respond_copy_v1(runtime, call, operation_id, status, body, body_len);
    if (body != stack_body) { free(body); }
    return err;
}

int hello_v1_greeter_lots_of_greetings_decode_request_receive(const trevrpc_rpc_receive* receive, Hello__V1__HelloRequest** out_message) {
    if (receive == NULL || out_message == NULL) { return -EINVAL; }
    trevrpc_rpc_receive_info_v1 info; int err = trevrpc_rpc_receive_info_v1_init(&info, sizeof(info));
    if (err == 0) { err = trevrpc_rpc_receive_get_info_v1(receive, &info); }
    if (err != 0) { return err; }
    if (info.kind != TREVRPC_RPC_RECEIVE_INITIAL_MESSAGE && info.kind != TREVRPC_RPC_RECEIVE_MESSAGE) { return -EPROTO; }
    if (info.data_len > SIZE_MAX) { return -EOVERFLOW; }
    trevrpc_generated_allocator_state allocator_state = {0};
    ProtobufCAllocator allocator = trevrpc_generated_allocator(&allocator_state);
    Hello__V1__HelloRequest* message = hello__v1__hello_request__unpack(&allocator, (size_t)info.data_len, info.data);
    if (message == NULL) { return allocator_state.failed ? -ENOMEM : -EPROTO; }
    *out_message = message;
    return 0;
}

int hello_v1_greeter_lots_of_greetings_decode_response_receive(const trevrpc_rpc_receive* receive, Hello__V1__HelloReply** out_message) {
    if (receive == NULL || out_message == NULL) { return -EINVAL; }
    trevrpc_rpc_receive_info_v1 info; int err = trevrpc_rpc_receive_info_v1_init(&info, sizeof(info));
    if (err == 0) { err = trevrpc_rpc_receive_get_info_v1(receive, &info); }
    if (err != 0) { return err; }
    if (info.kind != TREVRPC_RPC_RECEIVE_MESSAGE) { return -EPROTO; }
    if (info.data_len > SIZE_MAX) { return -EOVERFLOW; }
    trevrpc_generated_allocator_state allocator_state = {0};
    ProtobufCAllocator allocator = trevrpc_generated_allocator(&allocator_state);
    Hello__V1__HelloReply* message = hello__v1__hello_reply__unpack(&allocator, (size_t)info.data_len, info.data);
    if (message == NULL) { return allocator_state.failed ? -ENOMEM : -EPROTO; }
    *out_message = message;
    return 0;
}

int hello_v1_greeter_lots_of_greetings_matches_incoming(const trevrpc_rpc_event_info_v1* info) {
    if (info == NULL || info->kind != TREVRPC_RPC_EVENT_CALL_INCOMING || info->rpc_kind != TREVRPC_RPC_KIND_CLIENT_STREAMING) { return 0; }
    return info->service != NULL && info->method != NULL && info->service_len == sizeof("hello.v1.Greeter") - 1 && memcmp(info->service, "hello.v1.Greeter", sizeof("hello.v1.Greeter") - 1) == 0 && info->method_len == sizeof("LotsOfGreetings") - 1 && memcmp(info->method, "LotsOfGreetings", sizeof("LotsOfGreetings") - 1) == 0;
}

int hello_v1_greeter_lots_of_greetings_take_incoming(trevrpc_rpc_event* event, trevrpc_rpc_call_v1* out_call, trevrpc_rpc_stream_v1* out_stream, trevrpc_rpc_receive** out_initial) {
    if (event == NULL || out_call == NULL || out_stream == NULL || out_initial == NULL) { return -EINVAL; }
    trevrpc_rpc_event_info_v1 info; int err = trevrpc_rpc_event_info_v1_init(&info, sizeof(info));
    if (err == 0) { err = trevrpc_rpc_event_get_info_v1(event, &info); }
    if (err == 0 && !hello_v1_greeter_lots_of_greetings_matches_incoming(&info)) { err = -EPROTO; }
    if (err != 0) { return err; }
    trevrpc_rpc_call_v1 call = {0}; trevrpc_rpc_stream_v1 stream = {0}; trevrpc_rpc_receive* initial = NULL;
    err = trevrpc_rpc_event_take_incoming_call(event, &call, &stream, &initial);
    if (err != 0) { return err; }
    *out_call = call; *out_stream = stream; *out_initial = initial;
    return 0;
}

int hello_v1_greeter_lots_of_greetings_accept(trevrpc_rpc_runtime* runtime, trevrpc_rpc_call_v1 call, uint64_t operation_id) {
    if (runtime == NULL || operation_id == TREVRPC_RPC_OPERATION_ID_NONE) { return -EINVAL; }
    return trevrpc_rpc_call_accept(runtime, call, operation_id);
}

int hello_v1_greeter_bidi_hello_call_config_init(trevrpc_rpc_call_config_v1* config, size_t struct_size) {
    int err = trevrpc_rpc_call_config_v1_init(config, struct_size);
    if (err != 0) { return err; }
    config->kind = TREVRPC_RPC_KIND_BIDIRECTIONAL_STREAMING; config->service = "hello.v1.Greeter"; config->service_len = sizeof("hello.v1.Greeter") - 1;
    config->method = "BidiHello"; config->method_len = sizeof("BidiHello") - 1; return 0;
}

int hello_v1_greeter_bidi_hello_open(trevrpc_rpc_runtime* runtime, trevrpc_rpc_endpoint_v1 endpoint, const Hello__V1__HelloRequest* initial_or_null, uint64_t operation_id, trevrpc_rpc_call_v1* out_call, trevrpc_rpc_stream_v1* out_stream) {
    if (runtime == NULL || operation_id == TREVRPC_RPC_OPERATION_ID_NONE || out_call == NULL || out_stream == NULL) { return -EINVAL; }
    trevrpc_rpc_call_config_v1 config; int err = hello_v1_greeter_bidi_hello_call_config_init(&config, sizeof(config));
    if (err != 0) { return err; }
    uint8_t stack_body[TREVRPC_GENERATED_STACK_BODY_LEN]; uint8_t* body = NULL; size_t body_len = 0;
    if (initial_or_null != NULL) {
        body_len = hello__v1__hello_request__get_packed_size(initial_or_null);
        body = body_len == 0 ? stack_body : (body_len <= sizeof(stack_body) ? stack_body : malloc(body_len));
        if (body_len > 0 && body == NULL) { return -ENOMEM; }
        hello__v1__hello_request__pack(initial_or_null, body); config.initial_message = body; config.initial_message_len = body_len;
    }
    err = trevrpc_rpc_call_open_v1(runtime, endpoint, &config, operation_id, out_call, out_stream);
    if (initial_or_null != NULL) { if (body != stack_body) { free(body); } }
    return err;
}

int hello_v1_greeter_bidi_hello_send_request(trevrpc_rpc_runtime* runtime, trevrpc_rpc_stream_v1 stream, const Hello__V1__HelloRequest* message, uint64_t operation_id) {
    if (runtime == NULL || message == NULL || operation_id == TREVRPC_RPC_OPERATION_ID_NONE) { return -EINVAL; }
    size_t body_len = hello__v1__hello_request__get_packed_size(message);
    uint8_t stack_body[TREVRPC_GENERATED_STACK_BODY_LEN];
    uint8_t* body = body_len == 0 ? stack_body : (body_len <= sizeof(stack_body) ? stack_body : malloc(body_len));
    if (body_len > 0 && body == NULL) { return -ENOMEM; }
    hello__v1__hello_request__pack(message, body);
    int err = trevrpc_rpc_stream_send_copy_v1(runtime, stream, operation_id, body, body_len, TREVRPC_RPC_SEND_FLAG_NONE);
    if (body != stack_body) { free(body); }
    return err;
}

int hello_v1_greeter_bidi_hello_finish_send(trevrpc_rpc_runtime* runtime, trevrpc_rpc_stream_v1 stream, uint64_t operation_id) {
    if (runtime == NULL || operation_id == TREVRPC_RPC_OPERATION_ID_NONE) { return -EINVAL; }
    return trevrpc_rpc_stream_finish_send(runtime, stream, operation_id);
}

int hello_v1_greeter_bidi_hello_send_response(trevrpc_rpc_runtime* runtime, trevrpc_rpc_stream_v1 stream, const Hello__V1__HelloReply* message, uint64_t operation_id) {
    if (runtime == NULL || message == NULL || operation_id == TREVRPC_RPC_OPERATION_ID_NONE) { return -EINVAL; }
    size_t body_len = hello__v1__hello_reply__get_packed_size(message);
    uint8_t stack_body[TREVRPC_GENERATED_STACK_BODY_LEN];
    uint8_t* body = body_len == 0 ? stack_body : (body_len <= sizeof(stack_body) ? stack_body : malloc(body_len));
    if (body_len > 0 && body == NULL) { return -ENOMEM; }
    hello__v1__hello_reply__pack(message, body);
    int err = trevrpc_rpc_stream_send_copy_v1(runtime, stream, operation_id, body, body_len, TREVRPC_RPC_SEND_FLAG_NONE);
    if (body != stack_body) { free(body); }
    return err;
}

int hello_v1_greeter_bidi_hello_finish(trevrpc_rpc_runtime* runtime, trevrpc_rpc_call_v1 call, uint64_t operation_id, const trevrpc_rpc_status_v1* status) {
    if (runtime == NULL || status == NULL || operation_id == TREVRPC_RPC_OPERATION_ID_NONE) { return -EINVAL; }
    return trevrpc_rpc_call_finish_v1(runtime, call, operation_id, status);
}

int hello_v1_greeter_bidi_hello_decode_request_receive(const trevrpc_rpc_receive* receive, Hello__V1__HelloRequest** out_message) {
    if (receive == NULL || out_message == NULL) { return -EINVAL; }
    trevrpc_rpc_receive_info_v1 info; int err = trevrpc_rpc_receive_info_v1_init(&info, sizeof(info));
    if (err == 0) { err = trevrpc_rpc_receive_get_info_v1(receive, &info); }
    if (err != 0) { return err; }
    if (info.kind != TREVRPC_RPC_RECEIVE_INITIAL_MESSAGE && info.kind != TREVRPC_RPC_RECEIVE_MESSAGE) { return -EPROTO; }
    if (info.data_len > SIZE_MAX) { return -EOVERFLOW; }
    trevrpc_generated_allocator_state allocator_state = {0};
    ProtobufCAllocator allocator = trevrpc_generated_allocator(&allocator_state);
    Hello__V1__HelloRequest* message = hello__v1__hello_request__unpack(&allocator, (size_t)info.data_len, info.data);
    if (message == NULL) { return allocator_state.failed ? -ENOMEM : -EPROTO; }
    *out_message = message;
    return 0;
}

int hello_v1_greeter_bidi_hello_decode_response_receive(const trevrpc_rpc_receive* receive, Hello__V1__HelloReply** out_message) {
    if (receive == NULL || out_message == NULL) { return -EINVAL; }
    trevrpc_rpc_receive_info_v1 info; int err = trevrpc_rpc_receive_info_v1_init(&info, sizeof(info));
    if (err == 0) { err = trevrpc_rpc_receive_get_info_v1(receive, &info); }
    if (err != 0) { return err; }
    if (info.kind != TREVRPC_RPC_RECEIVE_MESSAGE) { return -EPROTO; }
    if (info.data_len > SIZE_MAX) { return -EOVERFLOW; }
    trevrpc_generated_allocator_state allocator_state = {0};
    ProtobufCAllocator allocator = trevrpc_generated_allocator(&allocator_state);
    Hello__V1__HelloReply* message = hello__v1__hello_reply__unpack(&allocator, (size_t)info.data_len, info.data);
    if (message == NULL) { return allocator_state.failed ? -ENOMEM : -EPROTO; }
    *out_message = message;
    return 0;
}

int hello_v1_greeter_bidi_hello_matches_incoming(const trevrpc_rpc_event_info_v1* info) {
    if (info == NULL || info->kind != TREVRPC_RPC_EVENT_CALL_INCOMING || info->rpc_kind != TREVRPC_RPC_KIND_BIDIRECTIONAL_STREAMING) { return 0; }
    return info->service != NULL && info->method != NULL && info->service_len == sizeof("hello.v1.Greeter") - 1 && memcmp(info->service, "hello.v1.Greeter", sizeof("hello.v1.Greeter") - 1) == 0 && info->method_len == sizeof("BidiHello") - 1 && memcmp(info->method, "BidiHello", sizeof("BidiHello") - 1) == 0;
}

int hello_v1_greeter_bidi_hello_take_incoming(trevrpc_rpc_event* event, trevrpc_rpc_call_v1* out_call, trevrpc_rpc_stream_v1* out_stream, trevrpc_rpc_receive** out_initial) {
    if (event == NULL || out_call == NULL || out_stream == NULL || out_initial == NULL) { return -EINVAL; }
    trevrpc_rpc_event_info_v1 info; int err = trevrpc_rpc_event_info_v1_init(&info, sizeof(info));
    if (err == 0) { err = trevrpc_rpc_event_get_info_v1(event, &info); }
    if (err == 0 && !hello_v1_greeter_bidi_hello_matches_incoming(&info)) { err = -EPROTO; }
    if (err != 0) { return err; }
    trevrpc_rpc_call_v1 call = {0}; trevrpc_rpc_stream_v1 stream = {0}; trevrpc_rpc_receive* initial = NULL;
    err = trevrpc_rpc_event_take_incoming_call(event, &call, &stream, &initial);
    if (err != 0) { return err; }
    *out_call = call; *out_stream = stream; *out_initial = initial;
    return 0;
}

int hello_v1_greeter_bidi_hello_accept(trevrpc_rpc_runtime* runtime, trevrpc_rpc_call_v1 call, uint64_t operation_id) {
    if (runtime == NULL || operation_id == TREVRPC_RPC_OPERATION_ID_NONE) { return -EINVAL; }
    return trevrpc_rpc_call_accept(runtime, call, operation_id);
}
