// Code generated by protoc-gen-trevrpc-c. DO NOT EDIT.
// clang-format off

#ifndef GREETER_TREVRPC_H
#define GREETER_TREVRPC_H

#include <stddef.h>
#include <stdint.h>
#include <protobuf-c/protobuf-c.h>
#include "trevrpc_rpc.h"
#include "greeter.pb-c.h"

#if TREVRPC_RPC_ABI_VERSION != 1u
#error "Generated TrevRPC C bindings require RPC ABI 1"
#endif

#ifdef __cplusplus
extern "C" {
#endif

#ifdef TREVRPC_GENERATED_TESTING
void trevrpc_hello_v1_greeter_proto_test_fail_allocation_after(size_t successful_allocations);
#endif

#define HELLO_V1_GREETER_SAY_HELLO_RPC_KIND TREVRPC_RPC_KIND_UNARY

int hello_v1_greeter_say_hello_call_config_init(trevrpc_rpc_call_config_v1* config, size_t struct_size);
int hello_v1_greeter_say_hello_open(trevrpc_rpc_runtime* runtime, trevrpc_rpc_endpoint_v1 endpoint, const Hello__V1__HelloRequest* initial_or_null, uint64_t operation_id, trevrpc_rpc_call_v1* out_call, trevrpc_rpc_stream_v1* out_stream);
int hello_v1_greeter_say_hello_respond(trevrpc_rpc_runtime* runtime, trevrpc_rpc_call_v1 call, const Hello__V1__HelloReply* message, const trevrpc_rpc_status_v1* status, uint64_t operation_id);
int hello_v1_greeter_say_hello_decode_request_receive(const trevrpc_rpc_receive* receive, Hello__V1__HelloRequest** out_message);
int hello_v1_greeter_say_hello_decode_response_receive(const trevrpc_rpc_receive* receive, Hello__V1__HelloReply** out_message);
int hello_v1_greeter_say_hello_matches_incoming(const trevrpc_rpc_event_info_v1* info);
/* On success, atomically transfers call, stream, and initial receive; outputs are unchanged on failure. Client-streaming and bidi initial receives may be empty and should be released without decoding. */
int hello_v1_greeter_say_hello_take_incoming(trevrpc_rpc_event* event, trevrpc_rpc_call_v1* out_call, trevrpc_rpc_stream_v1* out_stream, trevrpc_rpc_receive** out_initial);
int hello_v1_greeter_say_hello_accept(trevrpc_rpc_runtime* runtime, trevrpc_rpc_call_v1 call, uint64_t operation_id);

#define HELLO_V1_GREETER_LOTS_OF_REPLIES_RPC_KIND TREVRPC_RPC_KIND_SERVER_STREAMING

int hello_v1_greeter_lots_of_replies_call_config_init(trevrpc_rpc_call_config_v1* config, size_t struct_size);
int hello_v1_greeter_lots_of_replies_open(trevrpc_rpc_runtime* runtime, trevrpc_rpc_endpoint_v1 endpoint, const Hello__V1__HelloRequest* initial_or_null, uint64_t operation_id, trevrpc_rpc_call_v1* out_call, trevrpc_rpc_stream_v1* out_stream);
int hello_v1_greeter_lots_of_replies_send(trevrpc_rpc_runtime* runtime, trevrpc_rpc_stream_v1 stream, const Hello__V1__HelloReply* message, uint64_t operation_id);
int hello_v1_greeter_lots_of_replies_finish(trevrpc_rpc_runtime* runtime, trevrpc_rpc_call_v1 call, uint64_t operation_id, const trevrpc_rpc_status_v1* status);
int hello_v1_greeter_lots_of_replies_decode_request_receive(const trevrpc_rpc_receive* receive, Hello__V1__HelloRequest** out_message);
int hello_v1_greeter_lots_of_replies_decode_response_receive(const trevrpc_rpc_receive* receive, Hello__V1__HelloReply** out_message);
int hello_v1_greeter_lots_of_replies_matches_incoming(const trevrpc_rpc_event_info_v1* info);
/* On success, atomically transfers call, stream, and initial receive; outputs are unchanged on failure. Client-streaming and bidi initial receives may be empty and should be released without decoding. */
int hello_v1_greeter_lots_of_replies_take_incoming(trevrpc_rpc_event* event, trevrpc_rpc_call_v1* out_call, trevrpc_rpc_stream_v1* out_stream, trevrpc_rpc_receive** out_initial);
int hello_v1_greeter_lots_of_replies_accept(trevrpc_rpc_runtime* runtime, trevrpc_rpc_call_v1 call, uint64_t operation_id);

#define HELLO_V1_GREETER_LOTS_OF_GREETINGS_RPC_KIND TREVRPC_RPC_KIND_CLIENT_STREAMING

int hello_v1_greeter_lots_of_greetings_call_config_init(trevrpc_rpc_call_config_v1* config, size_t struct_size);
int hello_v1_greeter_lots_of_greetings_open(trevrpc_rpc_runtime* runtime, trevrpc_rpc_endpoint_v1 endpoint, const Hello__V1__HelloRequest* initial_or_null, uint64_t operation_id, trevrpc_rpc_call_v1* out_call, trevrpc_rpc_stream_v1* out_stream);
int hello_v1_greeter_lots_of_greetings_send(trevrpc_rpc_runtime* runtime, trevrpc_rpc_stream_v1 stream, const Hello__V1__HelloRequest* message, uint64_t operation_id);
int hello_v1_greeter_lots_of_greetings_finish_send(trevrpc_rpc_runtime* runtime, trevrpc_rpc_stream_v1 stream, uint64_t operation_id);
int hello_v1_greeter_lots_of_greetings_respond(trevrpc_rpc_runtime* runtime, trevrpc_rpc_call_v1 call, const Hello__V1__HelloReply* message, const trevrpc_rpc_status_v1* status, uint64_t operation_id);
int hello_v1_greeter_lots_of_greetings_decode_request_receive(const trevrpc_rpc_receive* receive, Hello__V1__HelloRequest** out_message);
int hello_v1_greeter_lots_of_greetings_decode_response_receive(const trevrpc_rpc_receive* receive, Hello__V1__HelloReply** out_message);
int hello_v1_greeter_lots_of_greetings_matches_incoming(const trevrpc_rpc_event_info_v1* info);
/* On success, atomically transfers call, stream, and initial receive; outputs are unchanged on failure. Client-streaming and bidi initial receives may be empty and should be released without decoding. */
int hello_v1_greeter_lots_of_greetings_take_incoming(trevrpc_rpc_event* event, trevrpc_rpc_call_v1* out_call, trevrpc_rpc_stream_v1* out_stream, trevrpc_rpc_receive** out_initial);
int hello_v1_greeter_lots_of_greetings_accept(trevrpc_rpc_runtime* runtime, trevrpc_rpc_call_v1 call, uint64_t operation_id);

#define HELLO_V1_GREETER_BIDI_HELLO_RPC_KIND TREVRPC_RPC_KIND_BIDIRECTIONAL_STREAMING

int hello_v1_greeter_bidi_hello_call_config_init(trevrpc_rpc_call_config_v1* config, size_t struct_size);
int hello_v1_greeter_bidi_hello_open(trevrpc_rpc_runtime* runtime, trevrpc_rpc_endpoint_v1 endpoint, const Hello__V1__HelloRequest* initial_or_null, uint64_t operation_id, trevrpc_rpc_call_v1* out_call, trevrpc_rpc_stream_v1* out_stream);
int hello_v1_greeter_bidi_hello_send_request(trevrpc_rpc_runtime* runtime, trevrpc_rpc_stream_v1 stream, const Hello__V1__HelloRequest* message, uint64_t operation_id);
int hello_v1_greeter_bidi_hello_finish_send(trevrpc_rpc_runtime* runtime, trevrpc_rpc_stream_v1 stream, uint64_t operation_id);
int hello_v1_greeter_bidi_hello_send_response(trevrpc_rpc_runtime* runtime, trevrpc_rpc_stream_v1 stream, const Hello__V1__HelloReply* message, uint64_t operation_id);
int hello_v1_greeter_bidi_hello_finish(trevrpc_rpc_runtime* runtime, trevrpc_rpc_call_v1 call, uint64_t operation_id, const trevrpc_rpc_status_v1* status);
int hello_v1_greeter_bidi_hello_decode_request_receive(const trevrpc_rpc_receive* receive, Hello__V1__HelloRequest** out_message);
int hello_v1_greeter_bidi_hello_decode_response_receive(const trevrpc_rpc_receive* receive, Hello__V1__HelloReply** out_message);
int hello_v1_greeter_bidi_hello_matches_incoming(const trevrpc_rpc_event_info_v1* info);
/* On success, atomically transfers call, stream, and initial receive; outputs are unchanged on failure. Client-streaming and bidi initial receives may be empty and should be released without decoding. */
int hello_v1_greeter_bidi_hello_take_incoming(trevrpc_rpc_event* event, trevrpc_rpc_call_v1* out_call, trevrpc_rpc_stream_v1* out_stream, trevrpc_rpc_receive** out_initial);
int hello_v1_greeter_bidi_hello_accept(trevrpc_rpc_runtime* runtime, trevrpc_rpc_call_v1 call, uint64_t operation_id);

#ifdef __cplusplus
}
#endif

#endif
