#[derive(Clone, PartialEq, prost::Message)]
pub struct HelloRequest {
    #[prost(string, tag = "1")]
    pub name: String,
}

#[derive(Clone, PartialEq, prost::Message)]
pub struct HelloReply {
    #[prost(string, tag = "1")]
    pub message: String,
}

// This file is @generated by protoc-gen-trevrpc-rust. DO NOT EDIT.

#[allow(clippy::missing_errors_doc)]
#[::trevrpc::async_trait]
pub trait Greeter: Send + Sync + 'static {
    /// Handles the `SayHello` RPC.
    async fn say_hello(
        &self,
        context: ::trevrpc::server::RequestContext,
        request: HelloRequest,
    ) -> ::core::result::Result<::trevrpc::ResponseEnvelope<HelloReply>, ::trevrpc::Status>;
    /// Handles the `LotsOfReplies` RPC.
    async fn lots_of_replies(
        &self,
        context: ::trevrpc::server::RequestContext,
        request: HelloRequest,
    ) -> ::core::result::Result<
        ::trevrpc::ResponseEnvelope<::trevrpc::BoxStream<HelloReply>>,
        ::trevrpc::Status,
    >;
    /// Handles the `LotsOfGreetings` RPC.
    async fn lots_of_greetings(
        &self,
        context: ::trevrpc::server::RequestContext,
        requests: ::trevrpc::BoxStream<HelloRequest>,
    ) -> ::core::result::Result<::trevrpc::ResponseEnvelope<HelloReply>, ::trevrpc::Status>;
    /// Handles the `BidiHello` RPC.
    async fn bidi_hello(
        &self,
        context: ::trevrpc::server::RequestContext,
        requests: ::trevrpc::BoxStream<HelloRequest>,
    ) -> ::core::result::Result<
        ::trevrpc::ResponseEnvelope<::trevrpc::BoxStream<HelloReply>>,
        ::trevrpc::Status,
    >;
}

#[derive(Clone)]
pub struct GreeterClient<T> {
    transport: T,
    default_options: ::trevrpc::client::CallOptions,
}

impl<T> GreeterClient<T> {
    pub const SERVICE: &'static str = "example.greeter.Greeter";

    /// Creates a client backed by the provided transport.
    #[must_use]
    pub fn new(transport: T) -> Self {
        Self {
            transport,
            default_options: ::trevrpc::client::CallOptions::new(),
        }
    }

    /// Creates a client with default call options applied to every RPC.
    #[must_use]
    pub fn with_default_call_options(
        transport: T,
        default_options: ::trevrpc::client::CallOptions,
    ) -> Self {
        Self {
            transport,
            default_options,
        }
    }

    /// Returns the default call options.
    #[must_use]
    pub const fn default_call_options(&self) -> &::trevrpc::client::CallOptions {
        &self.default_options
    }

    /// Returns the underlying transport.
    #[must_use]
    pub const fn transport(&self) -> &T {
        &self.transport
    }

    /// Consumes the client and returns the underlying transport.
    #[must_use]
    pub fn into_transport(self) -> T {
        self.transport
    }
}

#[allow(clippy::missing_errors_doc)]
impl<T> GreeterClient<T>
where
    T: ::trevrpc::client::RpcTransport,
{
    /// Calls the `SayHello` RPC.
    pub async fn say_hello(
        &self,
        request: HelloRequest,
    ) -> ::core::result::Result<HelloReply, ::trevrpc::Error> {
        self.say_hello_with_options(request, self.default_options.clone())
            .await
    }

    /// Calls the `SayHello` RPC with explicit call options.
    pub async fn say_hello_with_options(
        &self,
        request: HelloRequest,
        options: ::trevrpc::client::CallOptions,
    ) -> ::core::result::Result<HelloReply, ::trevrpc::Error> {
        ::trevrpc::client::unary(
            &self.transport,
            Self::SERVICE,
            "SayHello",
            &request,
            options,
        )
        .await
    }

    /// Calls the `SayHello` RPC and returns response metadata.
    pub async fn say_hello_envelope(
        &self,
        request: HelloRequest,
    ) -> ::core::result::Result<::trevrpc::ResponseEnvelope<HelloReply>, ::trevrpc::Error> {
        self.say_hello_envelope_with_options(request, self.default_options.clone())
            .await
    }

    /// Calls the `SayHello` RPC with explicit call options and returns response metadata.
    pub async fn say_hello_envelope_with_options(
        &self,
        request: HelloRequest,
        options: ::trevrpc::client::CallOptions,
    ) -> ::core::result::Result<::trevrpc::ResponseEnvelope<HelloReply>, ::trevrpc::Error> {
        ::trevrpc::client::unary_envelope(
            &self.transport,
            Self::SERVICE,
            "SayHello",
            &request,
            options,
        )
        .await
    }
}

#[allow(clippy::missing_errors_doc)]
impl<T> GreeterClient<T>
where
    T: ::trevrpc::client::StreamingRpcTransport,
{
    /// Calls the `LotsOfReplies` RPC.
    pub async fn lots_of_replies(
        &self,
        request: HelloRequest,
    ) -> ::core::result::Result<::trevrpc::client::ResponseStream<HelloReply>, ::trevrpc::Error>
    {
        self.lots_of_replies_with_options(request, self.default_options.clone())
            .await
    }

    /// Calls the `LotsOfReplies` RPC with explicit call options.
    pub async fn lots_of_replies_with_options(
        &self,
        request: HelloRequest,
        options: ::trevrpc::client::CallOptions,
    ) -> ::core::result::Result<::trevrpc::client::ResponseStream<HelloReply>, ::trevrpc::Error>
    {
        ::trevrpc::client::server_streaming(
            &self.transport,
            Self::SERVICE,
            "LotsOfReplies",
            &request,
            options,
        )
        .await
    }

    /// Calls the `LotsOfGreetings` RPC.
    pub async fn lots_of_greetings(
        &self,
    ) -> ::core::result::Result<
        ::trevrpc::client::ClientStreamingCall<HelloRequest, HelloReply>,
        ::trevrpc::Error,
    > {
        self.lots_of_greetings_with_options(self.default_options.clone())
            .await
    }

    /// Calls the `LotsOfGreetings` RPC with explicit call options.
    pub async fn lots_of_greetings_with_options(
        &self,
        options: ::trevrpc::client::CallOptions,
    ) -> ::core::result::Result<
        ::trevrpc::client::ClientStreamingCall<HelloRequest, HelloReply>,
        ::trevrpc::Error,
    > {
        ::trevrpc::client::client_streaming(
            &self.transport,
            Self::SERVICE,
            "LotsOfGreetings",
            options,
        )
        .await
    }

    /// Calls the `LotsOfGreetings` RPC with a caller-provided request stream.
    pub async fn lots_of_greetings_from_stream(
        &self,
        requests: ::trevrpc::BoxStream<HelloRequest>,
    ) -> ::core::result::Result<HelloReply, ::trevrpc::Error> {
        self.lots_of_greetings_from_stream_with_options(requests, self.default_options.clone())
            .await
    }

    /// Calls the `LotsOfGreetings` RPC with a caller-provided request stream and explicit call options.
    pub async fn lots_of_greetings_from_stream_with_options(
        &self,
        requests: ::trevrpc::BoxStream<HelloRequest>,
        options: ::trevrpc::client::CallOptions,
    ) -> ::core::result::Result<HelloReply, ::trevrpc::Error> {
        ::trevrpc::client::client_streaming_from_stream(
            &self.transport,
            Self::SERVICE,
            "LotsOfGreetings",
            requests,
            options,
        )
        .await
    }

    /// Calls the `LotsOfGreetings` RPC with a caller-provided request stream and preserves response metadata.
    pub async fn lots_of_greetings_from_stream_envelope(
        &self,
        requests: ::trevrpc::BoxStream<HelloRequest>,
    ) -> ::core::result::Result<::trevrpc::ResponseEnvelope<HelloReply>, ::trevrpc::Error> {
        self.lots_of_greetings_from_stream_envelope_with_options(
            requests,
            self.default_options.clone(),
        )
        .await
    }

    /// Calls the `LotsOfGreetings` RPC with a caller-provided request stream, explicit options, and response metadata.
    pub async fn lots_of_greetings_from_stream_envelope_with_options(
        &self,
        requests: ::trevrpc::BoxStream<HelloRequest>,
        options: ::trevrpc::client::CallOptions,
    ) -> ::core::result::Result<::trevrpc::ResponseEnvelope<HelloReply>, ::trevrpc::Error> {
        ::trevrpc::client::client_streaming_from_stream_envelope(
            &self.transport,
            Self::SERVICE,
            "LotsOfGreetings",
            requests,
            options,
        )
        .await
    }

    /// Calls the `BidiHello` RPC.
    pub async fn bidi_hello(
        &self,
    ) -> ::core::result::Result<
        ::trevrpc::client::BidirectionalCall<HelloRequest, HelloReply>,
        ::trevrpc::Error,
    > {
        self.bidi_hello_with_options(self.default_options.clone())
            .await
    }

    /// Calls the `BidiHello` RPC with explicit call options.
    pub async fn bidi_hello_with_options(
        &self,
        options: ::trevrpc::client::CallOptions,
    ) -> ::core::result::Result<
        ::trevrpc::client::BidirectionalCall<HelloRequest, HelloReply>,
        ::trevrpc::Error,
    > {
        ::trevrpc::client::bidirectional_streaming(
            &self.transport,
            Self::SERVICE,
            "BidiHello",
            options,
        )
        .await
    }

    /// Calls the `BidiHello` RPC with a caller-provided request stream.
    pub async fn bidi_hello_from_stream(
        &self,
        requests: ::trevrpc::BoxStream<HelloRequest>,
    ) -> ::core::result::Result<::trevrpc::client::ResponseStream<HelloReply>, ::trevrpc::Error>
    {
        self.bidi_hello_from_stream_with_options(requests, self.default_options.clone())
            .await
    }

    /// Calls the `BidiHello` RPC with a caller-provided request stream and explicit call options.
    pub async fn bidi_hello_from_stream_with_options(
        &self,
        requests: ::trevrpc::BoxStream<HelloRequest>,
        options: ::trevrpc::client::CallOptions,
    ) -> ::core::result::Result<::trevrpc::client::ResponseStream<HelloReply>, ::trevrpc::Error>
    {
        ::trevrpc::client::bidirectional_streaming_from_stream(
            &self.transport,
            Self::SERVICE,
            "BidiHello",
            requests,
            options,
        )
        .await
    }
}

/// Registers routes for the `example.greeter.Greeter` service.
pub fn register_greeter<S>(server: &mut ::trevrpc::server::Server, service: S)
where
    S: Greeter,
{
    let service = ::std::sync::Arc::new(service);

    {
        let service = ::std::sync::Arc::clone(&service);
        server.route_envelope_with_context(
            "example.greeter.Greeter",
            "SayHello",
            move |context, body| {
                let service = ::std::sync::Arc::clone(&service);
                async move {
                    let request = <HelloRequest as ::prost::Message>::decode(body.as_slice())?;
                    let response = service.say_hello(context, request).await?;
                    Ok(response.map(|response| ::prost::Message::encode_to_vec(&response)))
                }
            },
        );
    }

    {
        let service = ::std::sync::Arc::clone(&service);
        server.route_streaming_envelope_with_context(
            "example.greeter.Greeter",
            "LotsOfReplies",
            ::trevrpc::RpcKind::ServerStreaming,
            move |context, body, _request_stream| {
                let service = ::std::sync::Arc::clone(&service);
                async move {
                    let request = <HelloRequest as ::prost::Message>::decode(body.as_slice())?;
                    let responses = service.lots_of_replies(context, request).await?;
                    Ok(responses.map(::trevrpc::stream::encode))
                }
            },
        );
    }

    {
        let service = ::std::sync::Arc::clone(&service);
        server.route_streaming_envelope_with_context(
            "example.greeter.Greeter",
            "LotsOfGreetings",
            ::trevrpc::RpcKind::ClientStreaming,
            move |context, _body, request_stream| {
                let service = ::std::sync::Arc::clone(&service);
                async move {
                    let requests = ::trevrpc::stream::decode::<HelloRequest>(request_stream);
                    let response = service.lots_of_greetings(context, requests).await?;
                    Ok(response.map(|response| {
                        ::trevrpc::stream::encode(::trevrpc::stream::from_iter([response]))
                    }))
                }
            },
        );
    }

    {
        let service = ::std::sync::Arc::clone(&service);
        server.route_streaming_envelope_with_context(
            "example.greeter.Greeter",
            "BidiHello",
            ::trevrpc::RpcKind::BidirectionalStreaming,
            move |context, _body, request_stream| {
                let service = ::std::sync::Arc::clone(&service);
                async move {
                    let requests = ::trevrpc::stream::decode::<HelloRequest>(request_stream);
                    let responses = service.bidi_hello(context, requests).await?;
                    Ok(responses.map(::trevrpc::stream::encode))
                }
            },
        );
    }
}
