[package]
name = "trevrpc"
version = "0.1.0"
edition = "2024"
rust-version = "1.95.0"
description = "Protobuf over QUIC & WebTransport"
readme = "README.md"
repository = "https://trev.zip/llc/TrevRPC"
license-file = "LICENSE"

[lints.clippy]
pedantic = "warn"

[[bin]]
name = "trevrpc"
path = "main.rs"

[dependencies]
