#:schema https://www.schemastore.org/treefmt.json

[formatter.rustfmt]
command = "rustfmt"
options = ["--edition", "2024"]
includes = ["*.rs"]

[formatter.gofmt]
command = "gofmt"
options = ["-w"]
includes = ["*.go"]

[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]

[formatter.clang-format]
command = "clang-format"
options = ["-i"]
includes = ["*.c", "*.cc", "*.cpp", "*.h", "*.hpp"]

[formatter.ktlint]
command = "ktlint"
options = ["--format"]
includes = ["*.kt", "*.kts"]
excludes = ["trevrpc-kotlin/examples/generated/**"]

[formatter.oxfmt]
command = "oxfmt"
options = ["--write"]
includes = ["*.js", "*.ts", "*.html", "*.json", "*.yaml", "*.toml", "*.md"]
