[package]
name = "trevrpc-bench-peer"
version = "0.1.5"
edition = "2024"
rust-version = "1.95.0"
publish = false

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
module_name_repetitions = "allow"

[dependencies]
futures-util = "0.3"
prost = "0.14.4"
quinn = "0.11.11"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
tokio = { version = "1.48.0", features = [
  "io-std",
  "io-util",
  "macros",
  "net",
  "rt-multi-thread",
  "signal",
  "sync",
  "time",
] }
tokio-stream = { version = "0.1.17", features = ["net"] }
trevrpc = { path = "../..", default-features = false, features = [
  "client",
  "server",
  "quinn",
  "webtransport",
] }

[build-dependencies]
prost = "0.14.4"
prost-build = "0.14.4"
prost-types = "0.14.4"
protoc-gen-trevrpc-rust = { path = "../protoc-gen-trevrpc-rust" }
protox = "0.9.1"

[dev-dependencies]
rcgen = "0.14"
url = "2"
web-transport-quinn = { version = "0.11.9", default-features = false, features = ["ring"] }

[[bin]]
name = "trevrpc-bench-peer-rust"
path = "src/main.rs"
