#![forbid(unsafe_code)]
#![allow(
    clippy::format_push_string,
    clippy::missing_errors_doc,
    clippy::module_name_repetitions
)]

use std::collections::{BTreeMap, HashMap, HashSet};
use std::io::{self, Read, Write};

use heck::{ToSnakeCase, ToUpperCamelCase};
use prost::Message;
use prost_types::compiler::{CodeGeneratorRequest, CodeGeneratorResponse, code_generator_response};
use prost_types::{DescriptorProto, FileDescriptorProto, MethodDescriptorProto};

#[derive(Debug, Clone, PartialEq, Eq)]
struct PluginOptions {
    runtime_path: String,
    file_suffix: String,
    package_root: String,
}

impl Default for PluginOptions {
    fn default() -> Self {
        Self {
            runtime_path: "::trevrpc".to_owned(),
            file_suffix: ".trevrpc.rs".to_owned(),
            package_root: "crate".to_owned(),
        }
    }
}

pub fn run_plugin<R, W>(mut reader: R, mut writer: W) -> io::Result<()>
where
    R: Read,
    W: Write,
{
    let mut request = Vec::new();
    reader.read_to_end(&mut request)?;

    let request = CodeGeneratorRequest::decode(request.as_slice()).map_err(|error| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("failed to decode CodeGeneratorRequest: {error}"),
        )
    })?;

    let response = generate_plugin_response(&request);
    let mut output = Vec::new();
    response.encode(&mut output).map_err(|error| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("failed to encode CodeGeneratorResponse: {error}"),
        )
    })?;

    writer.write_all(&output)
}

#[must_use]
fn generate_plugin_response(request: &CodeGeneratorRequest) -> CodeGeneratorResponse {
    let options = match parse_plugin_options(request.parameter.as_deref()) {
        Ok(options) => options,
        Err(error) => {
            return CodeGeneratorResponse {
                error: Some(error),
                supported_features: Some(code_generator_response::Feature::Proto3Optional as u64),
                file: Vec::new(),
            };
        }
    };

    let files_to_generate = request
        .file_to_generate
        .iter()
        .map(String::as_str)
        .collect::<HashSet<_>>();
    let type_index = TypeIndex::from_files(&request.proto_file);
    let mut services_by_package = BTreeMap::<String, Vec<Service>>::new();

    for file in &request.proto_file {
        let Some(file_name) = file.name.as_deref() else {
            continue;
        };

        if !files_to_generate.contains(file_name) {
            continue;
        }

        let package = file.package.clone().unwrap_or_default();
        let services = file
            .service
            .iter()
            .map(|service| descriptor_service(&package, service, &type_index, &options))
            .collect::<Vec<_>>();

        services_by_package
            .entry(package)
            .or_default()
            .extend(services);
    }

    let file = services_by_package
        .into_iter()
        .filter(|(_, services)| !services.is_empty())
        .map(|(package, services)| {
            let mut content =
                "// This file is @generated by protoc-gen-trevrpc. DO NOT EDIT.\n\n".to_owned();

            for service in &services {
                generate_service(&options.runtime_path, service, &mut content);
                content.push('\n');
            }

            code_generator_response::File {
                name: Some(package_file_name(&package, &options.file_suffix)),
                insertion_point: None,
                content: Some(content),
                generated_code_info: None,
            }
        })
        .collect();

    CodeGeneratorResponse {
        error: None,
        supported_features: Some(code_generator_response::Feature::Proto3Optional as u64),
        file,
    }
}

fn parse_plugin_options(parameter: Option<&str>) -> Result<PluginOptions, String> {
    let mut options = PluginOptions::default();
    let Some(parameter) = parameter else {
        return Ok(options);
    };

    for option in parameter.split(',').filter(|option| !option.is_empty()) {
        let Some((key, value)) = option.split_once('=') else {
            return Err(format!(
                "invalid trevrpc option {option:?}; expected key=value"
            ));
        };

        match key {
            "runtime_path" => value.clone_into(&mut options.runtime_path),
            "file_suffix" => value.clone_into(&mut options.file_suffix),
            "package_root" => value.clone_into(&mut options.package_root),
            unknown => return Err(format!("unknown trevrpc option {unknown:?}")),
        }
    }

    Ok(options)
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct Service {
    name: String,
    proto_name: String,
    package: String,
    methods: Vec<Method>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct Method {
    name: String,
    proto_name: String,
    input_type: String,
    output_type: String,
    client_streaming: bool,
    server_streaming: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct TypeRef {
    package: String,
    rust_path: String,
}

#[derive(Debug, Default, Clone, PartialEq, Eq)]
struct TypeIndex {
    messages: HashMap<String, TypeRef>,
}

impl TypeIndex {
    fn from_files(files: &[FileDescriptorProto]) -> Self {
        let mut index = Self::default();

        for file in files {
            let package = file.package.as_deref().unwrap_or_default();

            for message in &file.message_type {
                index.index_message(package, Vec::new(), Vec::new(), message);
            }
        }

        index
    }

    fn index_message(
        &mut self,
        package: &str,
        mut proto_parents: Vec<String>,
        mut rust_parent_modules: Vec<String>,
        message: &DescriptorProto,
    ) {
        let Some(name) = message.name.as_deref() else {
            return;
        };
        let full_name = full_message_name(package, &proto_parents, name);
        let rust_type_name = to_rust_type_name(name);
        let rust_path = if rust_parent_modules.is_empty() {
            rust_type_name
        } else {
            format!("{}::{rust_type_name}", rust_parent_modules.join("::"))
        };

        self.messages.insert(
            full_name,
            TypeRef {
                package: package.to_owned(),
                rust_path,
            },
        );

        proto_parents.push(name.to_owned());
        rust_parent_modules.push(to_rust_ident(&name.to_snake_case()));

        for nested in &message.nested_type {
            self.index_message(
                package,
                proto_parents.clone(),
                rust_parent_modules.clone(),
                nested,
            );
        }
    }

    fn resolve(&self, current_package: &str, proto_type: &str, package_root: &str) -> String {
        let proto_type = if proto_type.starts_with('.') {
            proto_type.to_owned()
        } else if current_package.is_empty() {
            format!(".{proto_type}")
        } else {
            format!(".{current_package}.{proto_type}")
        };

        let Some(type_ref) = self.messages.get(&proto_type) else {
            return proto_type
                .rsplit('.')
                .next()
                .map_or_else(|| "()".to_owned(), to_rust_type_name);
        };

        if type_ref.package == current_package {
            return type_ref.rust_path.clone();
        }

        let package_modules = type_ref.package.split('.').map(to_rust_module_name);
        let mut path = Vec::new();
        path.push(package_root.trim_end_matches("::").to_owned());
        path.extend(package_modules);
        path.push(type_ref.rust_path.clone());
        path.join("::")
    }
}

fn descriptor_service(
    package: &str,
    service: &prost_types::ServiceDescriptorProto,
    type_index: &TypeIndex,
    options: &PluginOptions,
) -> Service {
    let proto_name = service.name.clone().unwrap_or_default();

    Service {
        name: to_rust_type_name(&proto_name),
        proto_name,
        package: package.to_owned(),
        methods: service
            .method
            .iter()
            .map(|method| descriptor_method(package, method, type_index, options))
            .collect(),
    }
}

fn descriptor_method(
    package: &str,
    method: &MethodDescriptorProto,
    type_index: &TypeIndex,
    options: &PluginOptions,
) -> Method {
    let proto_name = method.name.clone().unwrap_or_default();
    let input_proto_type = method.input_type.clone().unwrap_or_default();
    let output_proto_type = method.output_type.clone().unwrap_or_default();

    Method {
        name: to_rust_method_name(&proto_name),
        proto_name,
        input_type: type_index.resolve(package, &input_proto_type, &options.package_root),
        output_type: type_index.resolve(package, &output_proto_type, &options.package_root),
        client_streaming: method.client_streaming.unwrap_or_default(),
        server_streaming: method.server_streaming.unwrap_or_default(),
    }
}

fn generate_service(runtime_path: &str, service: &Service, buf: &mut String) {
    let unsupported_methods = service
        .methods
        .iter()
        .filter(|method| method.client_streaming || method.server_streaming);

    for method in unsupported_methods {
        let message = format!(
            "TrevRPC only supports unary RPCs right now: {}.{}",
            service.proto_name, method.proto_name
        );
        buf.push_str(&format!("compile_error!({message:?});\n"));
    }

    if service
        .methods
        .iter()
        .any(|method| method.client_streaming || method.server_streaming)
    {
        return;
    }

    generate_trait(runtime_path, service, buf);
    generate_client(runtime_path, service, buf);
    generate_registration(runtime_path, service, buf);
}

fn generate_trait(runtime_path: &str, service: &Service, buf: &mut String) {
    buf.push_str(&format!(
        "#[allow(clippy::missing_errors_doc)]\n#[{runtime_path}::async_trait]\npub trait {}: Send + Sync + 'static {{\n",
        service.name
    ));

    for method in &service.methods {
        buf.push_str(&format!(
            "    async fn {}(&self, request: {}) -> ::core::result::Result<{}, {runtime_path}::Status>;\n",
            method.name, method.input_type, method.output_type
        ));
    }

    buf.push_str("}\n\n");
}

fn generate_client(runtime_path: &str, service: &Service, buf: &mut String) {
    let client_name = format!("{}Client", service.name);
    let service_name = service_path(service);

    buf.push_str(&format!(
        "#[derive(Clone)]\npub struct {client_name}<T> {{\n    transport: T,\n}}\n\n"
    ));

    buf.push_str(&format!(
        "impl<T> {client_name}<T> {{\n    pub const SERVICE: &'static str = {service_name:?};\n\n    #[must_use]\n    pub fn new(transport: T) -> Self {{\n        Self {{ transport }}\n    }}\n\n    #[must_use]\n    pub const fn transport(&self) -> &T {{\n        &self.transport\n    }}\n\n    #[must_use]\n    pub fn into_transport(self) -> T {{\n        self.transport\n    }}\n}}\n\n"
    ));

    buf.push_str(&format!(
        "#[allow(clippy::missing_errors_doc)]\nimpl<T> {client_name}<T>\nwhere\n    T: {runtime_path}::client::RpcTransport,\n{{\n"
    ));

    for method in &service.methods {
        generate_client_method(runtime_path, method, buf);
    }

    buf.push_str("}\n\n");
}

fn generate_client_method(runtime_path: &str, method: &Method, buf: &mut String) {
    buf.push_str(&format!(
        "    pub async fn {}(&self, request: {}) -> ::core::result::Result<{}, {runtime_path}::Error> {{\n        {runtime_path}::client::unary(&self.transport, Self::SERVICE, {:?}, &request).await\n    }}\n\n    pub async fn {}_with_options(\n        &self,\n        request: {},\n        options: {runtime_path}::client::CallOptions,\n    ) -> ::core::result::Result<{}, {runtime_path}::Error> {{\n        {runtime_path}::client::unary_with_options(&self.transport, Self::SERVICE, {:?}, &request, options).await\n    }}\n\n",
        method.name,
        method.input_type,
        method.output_type,
        method.proto_name,
        method.name, method.input_type, method.output_type, method.proto_name
    ));
}

fn generate_registration(runtime_path: &str, service: &Service, buf: &mut String) {
    let register_name = format!("register_{}", to_snake_case(&service.name));
    let service_name = service_path(service);

    buf.push_str(&format!(
        "pub fn {register_name}<S>(server: &mut {runtime_path}::server::Server, service: S)\nwhere\n    S: {},\n{{\n    let service = ::std::sync::Arc::new(service);\n",
        service.name
    ));

    for method in &service.methods {
        generate_registration_method(&service_name, method, buf);
    }

    buf.push_str("}\n");
}

fn generate_registration_method(service_name: &str, method: &Method, buf: &mut String) {
    buf.push_str(&format!(
        "\n    {{\n        let service = ::std::sync::Arc::clone(&service);\n        server.route({service_name:?}, {:?}, move |body| {{\n            let service = ::std::sync::Arc::clone(&service);\n            async move {{\n                let request = <{} as ::prost::Message>::decode(body.as_slice())?;\n                let response = service.{}(request).await?;\n                Ok(::prost::Message::encode_to_vec(&response))\n            }}\n        }});\n    }}\n",
        method.proto_name, method.input_type, method.name
    ));
}

fn service_path(service: &Service) -> String {
    if service.package.is_empty() {
        service.proto_name.clone()
    } else {
        format!("{}.{}", service.package, service.proto_name)
    }
}

fn package_file_name(package: &str, suffix: &str) -> String {
    if package.is_empty() {
        format!("_{suffix}")
    } else {
        format!("{package}{suffix}")
    }
}

fn full_message_name(package: &str, parents: &[String], name: &str) -> String {
    let mut parts = Vec::new();

    if !package.is_empty() {
        parts.push(package);
    }

    parts.extend(parents.iter().map(String::as_str));
    parts.push(name);

    format!(".{}", parts.join("."))
}

fn to_rust_type_name(input: &str) -> String {
    to_rust_ident(&input.to_upper_camel_case())
}

fn to_rust_method_name(input: &str) -> String {
    to_rust_ident(&input.to_snake_case())
}

fn to_rust_module_name(input: &str) -> String {
    to_rust_ident(&input.to_snake_case())
}

fn to_rust_ident(input: &str) -> String {
    let ident = input.trim_matches('_');
    let ident = if ident.is_empty() { "_" } else { ident };

    if RUST_KEYWORDS.contains(&ident) {
        format!("r#{ident}")
    } else {
        ident.to_owned()
    }
}

const RUST_KEYWORDS: &[&str] = &[
    "Self", "abstract", "as", "async", "await", "become", "box", "break", "const", "continue",
    "crate", "do", "dyn", "else", "enum", "extern", "false", "final", "fn", "for", "if", "impl",
    "in", "let", "loop", "macro", "match", "mod", "move", "mut", "override", "priv", "pub", "ref",
    "return", "self", "static", "struct", "super", "trait", "true", "try", "type", "typeof",
    "unsafe", "unsized", "use", "virtual", "where", "while", "yield",
];

fn to_snake_case(input: &str) -> String {
    let mut output = String::with_capacity(input.len());

    for (index, character) in input.chars().enumerate() {
        if character.is_uppercase() {
            if index > 0 {
                output.push('_');
            }
            output.extend(character.to_lowercase());
        } else {
            output.push(character);
        }
    }

    output
}

#[cfg(test)]
mod tests {
    use prost::Message;
    use prost_types::compiler::CodeGeneratorRequest;
    use prost_types::{DescriptorProto, FileDescriptorProto, MethodDescriptorProto};

    use super::{
        Service, generate_plugin_response, generate_service, package_file_name, service_path,
        to_rust_method_name, to_snake_case,
    };

    use super::Method;

    #[test]
    fn builds_proto_service_paths() {
        let service = Service {
            name: "Greeter".to_owned(),
            proto_name: "Greeter".to_owned(),
            package: "hello.v1".to_owned(),
            methods: Vec::new(),
        };

        assert_eq!(service_path(&service), "hello.v1.Greeter");
    }

    #[test]
    fn converts_service_names_to_register_function_names() {
        assert_eq!(to_snake_case("Greeter"), "greeter");
        assert_eq!(to_snake_case("ChatService"), "chat_service");
    }

    #[test]
    fn builds_plugin_file_names() {
        assert_eq!(
            package_file_name("hello.v1", ".trevrpc.rs"),
            "hello.v1.trevrpc.rs"
        );
        assert_eq!(package_file_name("", ".trevrpc.rs"), "_.trevrpc.rs");
    }

    #[test]
    fn escapes_rust_method_keywords() {
        assert_eq!(to_rust_method_name("Type"), "r#type");
    }

    #[test]
    fn generates_unary_service_api() {
        let service = Service {
            name: "Greeter".to_owned(),
            proto_name: "Greeter".to_owned(),
            package: "hello.v1".to_owned(),
            methods: vec![Method {
                name: "say_hello".to_owned(),
                proto_name: "SayHello".to_owned(),
                input_type: "HelloRequest".to_owned(),
                output_type: "HelloReply".to_owned(),
                client_streaming: false,
                server_streaming: false,
            }],
        };
        let mut generated = String::new();

        generate_service("::trevrpc", &service, &mut generated);

        assert!(generated.contains("pub trait Greeter"));
        assert!(generated.contains("pub struct GreeterClient<T>"));
        assert!(generated.contains("pub fn register_greeter<S>"));
        assert!(generated.contains("hello.v1.Greeter"));
        assert!(generated.contains("SayHello"));
    }

    #[test]
    fn plugin_generates_package_service_file() {
        let request = hello_request(None);

        let response = generate_plugin_response(&request);

        assert_eq!(response.error, None);
        assert_eq!(response.file.len(), 1);
        assert_eq!(
            response.file[0].name.as_deref(),
            Some("hello.v1.trevrpc.rs")
        );

        let content = response.file[0]
            .content
            .as_deref()
            .expect("plugin should generate file content");

        assert!(content.contains("pub trait Greeter"));
        assert!(content.contains("pub struct GreeterClient<T>"));
        assert!(content.contains("pub fn register_greeter<S>"));
        assert!(content.contains("async fn say_hello"));
        assert!(content.contains("async fn say_hello_with_options"));
        assert!(content.contains("HelloRequest"));
        assert!(content.contains("HelloReply"));
    }

    #[test]
    fn plugin_accepts_generation_options() {
        let request = hello_request(Some(
            "runtime_path=::my_rpc,file_suffix=.rpc.rs,package_root=crate::pb".to_owned(),
        ));

        let response = generate_plugin_response(&request);

        assert_eq!(response.error, None);
        assert_eq!(response.file[0].name.as_deref(), Some("hello.v1.rpc.rs"));
        assert!(
            response.file[0]
                .content
                .as_deref()
                .expect("plugin should generate file content")
                .contains("::my_rpc::client::RpcTransport")
        );
    }

    #[test]
    fn plugin_reports_bad_options_in_response() {
        let request = hello_request(Some("bad".to_owned()));
        let response = generate_plugin_response(&request);

        assert!(response.error.is_some());
        assert!(response.file.is_empty());
    }

    #[test]
    fn plugin_round_trips_codegen_protocol() {
        let mut input = Vec::new();
        hello_request(None)
            .encode(&mut input)
            .expect("request should encode");
        let mut output = Vec::new();

        super::run_plugin(input.as_slice(), &mut output).expect("plugin should run");

        let response = prost_types::compiler::CodeGeneratorResponse::decode(output.as_slice())
            .expect("response should decode");

        assert_eq!(response.error, None);
        assert_eq!(response.file.len(), 1);
    }

    fn hello_request(parameter: Option<String>) -> CodeGeneratorRequest {
        CodeGeneratorRequest {
            file_to_generate: vec!["proto/hello.proto".to_owned()],
            parameter,
            proto_file: vec![FileDescriptorProto {
                name: Some("proto/hello.proto".to_owned()),
                package: Some("hello.v1".to_owned()),
                message_type: vec![message("HelloRequest"), message("HelloReply")],
                service: vec![prost_types::ServiceDescriptorProto {
                    name: Some("Greeter".to_owned()),
                    method: vec![MethodDescriptorProto {
                        name: Some("SayHello".to_owned()),
                        input_type: Some(".hello.v1.HelloRequest".to_owned()),
                        output_type: Some(".hello.v1.HelloReply".to_owned()),
                        options: None,
                        client_streaming: Some(false),
                        server_streaming: Some(false),
                    }],
                    options: None,
                }],
                ..Default::default()
            }],
            compiler_version: None,
        }
    }

    fn message(name: &str) -> DescriptorProto {
        DescriptorProto {
            name: Some(name.to_owned()),
            ..Default::default()
        }
    }
}
