[package]
name = "protoc-gen-trevrpc"
version = "0.1.0"
edition = "2024"
rust-version = "1.95.0"
description = "Buf/protoc plugin for TrevRPC service code generation"
readme = "../../README.md"
repository = "https://trev.zip/llc/TrevRPC"
license-file = "../../LICENSE"

[lints.clippy]
pedantic = "warn"

[dependencies]
heck = "0.5.0"
prost = "0.13.5"
prost-types = "0.13.5"
