package main

import (
	"fmt"
	"go/token"
	"io"
	"os"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	plugin "google.golang.org/protobuf/types/pluginpb"
)

type pluginOptions struct {
	runtimeImport protogen.GoImportPath
	fileSuffix    string
	servicePrefix string
}

func defaultPluginOptions() pluginOptions {
	return pluginOptions{
		runtimeImport: "trev.zip/llc/trevrpc/trevrpc-go",
		fileSuffix:    ".trevrpc.go",
	}
}

func (o *pluginOptions) set(name, value string) error {
	switch name {
	case "runtime_import":
		o.runtimeImport = protogen.GoImportPath(value)
	case "file_suffix":
		o.fileSuffix = value
	case "service_prefix":
		o.servicePrefix = value
	default:
		return fmt.Errorf("unknown trevrpc-go option %q", name)
	}
	return nil
}

func (o pluginOptions) validate() error {
	if o.runtimeImport == "" || (!strings.Contains(string(o.runtimeImport), ".") && !strings.Contains(string(o.runtimeImport), "/")) {
		return fmt.Errorf("invalid runtime_import %q: expected a usable Go import path", o.runtimeImport)
	}
	if o.fileSuffix == "" {
		return fmt.Errorf("file_suffix must not be empty")
	}
	if o.servicePrefix != "" && !token.IsIdentifier(o.servicePrefix+"Service") {
		return fmt.Errorf("invalid service_prefix %q: expected a Go identifier prefix", o.servicePrefix)
	}
	return nil
}

func main() {
	if err := run(os.Stdin, os.Stdout); err != nil {
		fmt.Fprintf(os.Stderr, "protoc-gen-trevrpc-go: %v\n", err)
		os.Exit(1)
	}
}

func run(reader io.Reader, writer io.Writer) error {
	input, err := io.ReadAll(reader)
	if err != nil {
		return err
	}

	request := &plugin.CodeGeneratorRequest{}
	if err := proto.Unmarshal(input, request); err != nil {
		return fmt.Errorf("decode CodeGeneratorRequest: %w", err)
	}

	response := generate(request)
	output, err := proto.Marshal(response)
	if err != nil {
		return fmt.Errorf("encode CodeGeneratorResponse: %w", err)
	}

	_, err = writer.Write(output)
	return err
}

func generate(request *plugin.CodeGeneratorRequest) *plugin.CodeGeneratorResponse {
	request = withDefaultSourceRelative(request)
	options := defaultPluginOptions()
	generator, err := (protogen.Options{ParamFunc: options.set}).New(request)
	if err != nil {
		return &plugin.CodeGeneratorResponse{Error: new(err.Error())}
	}
	if err := options.validate(); err != nil {
		return &plugin.CodeGeneratorResponse{Error: new(err.Error())}
	}
	if err := validateGeneratedNames(generator.Files, options); err != nil {
		return &plugin.CodeGeneratorResponse{Error: new(err.Error())}
	}

	for _, file := range generator.Files {
		if !file.Generate || len(file.Services) == 0 {
			continue
		}
		if err := generateFile(generator, file, options); err != nil {
			generator.Error(err)
			break
		}
	}
	return generator.Response()
}

func withDefaultSourceRelative(request *plugin.CodeGeneratorRequest) *plugin.CodeGeneratorRequest {
	clone := proto.Clone(request).(*plugin.CodeGeneratorRequest)
	for parameter := range strings.SplitSeq(clone.GetParameter(), ",") {
		name, _, _ := strings.Cut(parameter, "=")
		if name == "paths" || name == "module" {
			return clone
		}
	}
	if clone.GetParameter() == "" {
		clone.Parameter = new("paths=source_relative")
	} else {
		clone.Parameter = new(clone.GetParameter() + ",paths=source_relative")
	}
	return clone
}

type fileGenerator struct {
	generated *protogen.GeneratedFile
	options   pluginOptions
}

func generateFile(plugin *protogen.Plugin, file *protogen.File, options pluginOptions) error {
	generated := plugin.NewGeneratedFile(file.GeneratedFilenamePrefix+options.fileSuffix, file.GoImportPath)
	g := fileGenerator{generated: generated, options: options}
	generated.P("// Code generated by protoc-gen-trevrpc-go. DO NOT EDIT.")
	generated.P()
	generated.P("package ", file.GoPackageName)
	generated.P()

	for _, service := range file.Services {
		g.generateService(service)
	}
	return nil
}

func validateGeneratedNames(files []*protogen.File, options pluginOptions) error {
	packageOwners := make(map[protogen.GoImportPath]map[string]*protogen.Service)
	for _, file := range files {
		if !file.Generate || len(file.Services) == 0 {
			continue
		}
		owners := packageOwners[file.GoImportPath]
		if owners == nil {
			owners = make(map[string]*protogen.Service)
			packageOwners[file.GoImportPath] = owners
		}

		for _, service := range file.Services {
			if err := validateGeneratedMethodNames(service); err != nil {
				return err
			}
			for _, generatedName := range generatedServiceNames(service, options) {
				if owner, exists := owners[generatedName]; exists && owner != service {
					return fmt.Errorf("go package %s services %s and %s both require generated declaration %s", file.GoImportPath, owner.Desc.FullName(), service.Desc.FullName(), generatedName)
				}
				owners[generatedName] = service
			}
		}
	}
	return nil
}

func generatedServiceNames(service *protogen.Service, options pluginOptions) []string {
	serviceName := options.servicePrefix + service.GoName
	serverName := serviceName + "Server"
	clientName := serviceName + "Client"
	names := []string{
		serverName,
		clientName,
		"New" + clientName,
		"Register" + serverName,
		"(*" + clientName + ").mergedCallOptions",
	}
	for _, method := range service.Methods {
		for _, methodName := range generatedClientMethodNames(method) {
			names = append(names, "(*"+clientName+")."+methodName)
		}
	}
	return names
}

func validateGeneratedMethodNames(service *protogen.Service) error {
	owners := make(map[string]*protogen.Method)
	for _, method := range service.Methods {
		for _, generatedName := range generatedClientMethodNames(method) {
			if owner, exists := owners[generatedName]; exists && owner != method {
				return fmt.Errorf("service %s RPC methods %s and %s (%s and %s) both require generated Go method %s", service.Desc.FullName(), owner.GoName, method.GoName, owner.Desc.FullName(), method.Desc.FullName(), generatedName)
			}
			owners[generatedName] = method
		}
	}
	return nil
}

func generatedClientMethodNames(method *protogen.Method) []string {
	names := []string{method.GoName, method.GoName + "Response"}
	if method.Desc.IsStreamingClient() {
		names = append(names, method.GoName+"FromStream", method.GoName+"FromStreamResponse")
	}
	return names
}

func (g fileGenerator) generateService(service *protogen.Service) {
	serviceName := g.options.servicePrefix + service.GoName
	serverName := serviceName + "Server"
	clientName := serviceName + "Client"
	fullServiceName := string(service.Desc.FullName())
	contextType := g.qualified(protogen.GoImportPath("context").Ident("Context"))

	g.generated.P("// ", serverName, " handles the ", service.GoName, " service.")
	g.generated.P("type ", serverName, " interface {")
	for _, method := range service.Methods {
		g.generated.P("// ", method.GoName, " handles the ", method.Desc.Name(), " RPC.")
		g.generated.P(method.GoName, "(", contextType, ", ", g.serverRequestType(method), ") (", g.serverResponseType(method), ", error)")
	}
	g.generated.P("}")
	g.generated.P()

	g.generated.P("// ", clientName, " calls the ", service.GoName, " service.")
	g.generated.P("type ", clientName, " struct {")
	g.generated.P("transport ", g.runtime("Transport"))
	g.generated.P("options []", g.runtime("CallOption"))
	g.generated.P("}")
	g.generated.P()
	g.generated.P("// New", clientName, " creates a client for the ", service.GoName, " service.")
	g.generated.P("func New", clientName, "(transport ", g.runtime("Transport"), ", options ...", g.runtime("CallOption"), ") *", clientName, " {")
	g.generated.P("return &", clientName, "{transport: transport, options: options}")
	g.generated.P("}")
	g.generated.P()
	g.generateMergeOptions(clientName)

	for _, method := range service.Methods {
		g.generateClientMethods(clientName, fullServiceName, method)
	}

	g.generated.P("// Register", serverName, " registers handlers for the ", service.GoName, " service.")
	g.generated.P("func Register", serverName, "(server *", g.runtime("Server"), ", implementation ", serverName, ") {")
	for _, method := range service.Methods {
		g.generateServerRegistration(fullServiceName, method)
	}
	g.generated.P("}")
	g.generated.P()
}

func (g fileGenerator) generateMergeOptions(clientName string) {
	callOption := g.runtime("CallOption")
	g.generated.P("func (c *", clientName, ") mergedCallOptions(overrides []", callOption, ") []", callOption, " {")
	g.generated.P("if len(c.options) == 0 {")
	g.generated.P("return overrides")
	g.generated.P("}")
	g.generated.P("if len(overrides) == 0 {")
	g.generated.P("return c.options")
	g.generated.P("}")
	g.generated.P("merged := make([]", callOption, ", 0, len(c.options)+len(overrides))")
	g.generated.P("merged = append(merged, c.options...)")
	g.generated.P("merged = append(merged, overrides...)")
	g.generated.P("return merged")
	g.generated.P("}")
	g.generated.P()
}

func (g fileGenerator) generateClientMethods(clientName, serviceName string, method *protogen.Method) {
	contextType := g.qualified(protogen.GoImportPath("context").Ident("Context"))
	inputType := g.messageType(method.Input)
	outputType := g.messageType(method.Output)
	factory := g.messageFactory(method.Output)
	options := "options ..." + g.runtime("CallOption")
	merged := "c.mergedCallOptions(options)..."
	methodName := method.GoName
	protoMethodName := string(method.Desc.Name())

	g.generated.P("// ", methodName, " calls the ", method.Desc.Name(), " RPC.")
	switch {
	case method.Desc.IsStreamingClient() && method.Desc.IsStreamingServer():
		g.generated.P("func (c *", clientName, ") ", methodName, "(ctx ", contextType, ", ", options, ") (", g.runtime("BidirectionalStreamingCall"), "[", inputType, ", ", outputType, "], error) {")
		g.generated.P("return ", g.runtime("BidirectionalStreaming"), "[", inputType, ", ", outputType, "](ctx, c.transport, ", quoted(serviceName), ", ", quoted(protoMethodName), ", ", factory, ", ", merged, ")")
		g.generated.P("}")
		g.generated.P()
		g.generated.P("// ", methodName, "Response calls the ", method.Desc.Name(), " RPC and exposes terminal metadata.")
		g.generated.P("func (c *", clientName, ") ", methodName, "Response(ctx ", contextType, ", ", options, ") (", g.runtime("BidirectionalStreamingResponseCall"), "[", inputType, ", ", outputType, "], error) {")
		g.generated.P("return ", g.runtime("BidirectionalStreamingResponse"), "[", inputType, ", ", outputType, "](ctx, c.transport, ", quoted(serviceName), ", ", quoted(protoMethodName), ", ", factory, ", ", merged, ")")
		g.generated.P("}")
		g.generated.P()
		g.generateBidiFromStreamMethods(clientName, serviceName, protoMethodName, methodName, contextType, inputType, outputType, factory, options, merged)
	case method.Desc.IsStreamingClient():
		g.generated.P("func (c *", clientName, ") ", methodName, "(ctx ", contextType, ", ", options, ") (", g.runtime("ClientStreamingCall"), "[", inputType, ", ", outputType, "], error) {")
		g.generated.P("return ", g.runtime("ClientStreaming"), "[", inputType, ", ", outputType, "](ctx, c.transport, ", quoted(serviceName), ", ", quoted(protoMethodName), ", ", factory, ", ", merged, ")")
		g.generated.P("}")
		g.generated.P()
		g.generated.P("// ", methodName, "Response calls the ", method.Desc.Name(), " RPC and exposes response metadata.")
		g.generated.P("func (c *", clientName, ") ", methodName, "Response(ctx ", contextType, ", ", options, ") (", g.runtime("ClientStreamingResponseCall"), "[", inputType, ", ", outputType, "], error) {")
		g.generated.P("return ", g.runtime("ClientStreamingResponse"), "[", inputType, ", ", outputType, "](ctx, c.transport, ", quoted(serviceName), ", ", quoted(protoMethodName), ", ", factory, ", ", merged, ")")
		g.generated.P("}")
		g.generated.P()
		g.generateClientFromStreamMethods(clientName, serviceName, protoMethodName, methodName, contextType, inputType, outputType, factory, options, merged)
	case method.Desc.IsStreamingServer():
		g.generated.P("func (c *", clientName, ") ", methodName, "(ctx ", contextType, ", request ", inputType, ", ", options, ") (", g.runtime("MessageStream"), "[", outputType, "], error) {")
		g.generated.P("return ", g.runtime("ServerStreaming"), "[", inputType, ", ", outputType, "](ctx, c.transport, ", quoted(serviceName), ", ", quoted(protoMethodName), ", request, ", factory, ", ", merged, ")")
		g.generated.P("}")
		g.generated.P()
		g.generated.P("// ", methodName, "Response calls the ", method.Desc.Name(), " RPC and exposes terminal metadata.")
		g.generated.P("func (c *", clientName, ") ", methodName, "Response(ctx ", contextType, ", request ", inputType, ", ", options, ") (", g.runtime("ResponseStream"), "[", outputType, "], error) {")
		g.generated.P("return ", g.runtime("ServerStreamingResponse"), "[", inputType, ", ", outputType, "](ctx, c.transport, ", quoted(serviceName), ", ", quoted(protoMethodName), ", request, ", factory, ", ", merged, ")")
		g.generated.P("}")
		g.generated.P()
	default:
		g.generated.P("func (c *", clientName, ") ", methodName, "(ctx ", contextType, ", request ", inputType, ", ", options, ") (", outputType, ", error) {")
		g.generated.P("return ", g.runtime("Unary"), "[", inputType, ", ", outputType, "](ctx, c.transport, ", quoted(serviceName), ", ", quoted(protoMethodName), ", request, ", factory, ", ", merged, ")")
		g.generated.P("}")
		g.generated.P()
		g.generated.P("// ", methodName, "Response calls the ", method.Desc.Name(), " RPC and exposes response metadata.")
		g.generated.P("func (c *", clientName, ") ", methodName, "Response(ctx ", contextType, ", request ", inputType, ", ", options, ") (*", g.runtime("Response"), "[", outputType, "], error) {")
		g.generated.P("return ", g.runtime("UnaryResponse"), "[", inputType, ", ", outputType, "](ctx, c.transport, ", quoted(serviceName), ", ", quoted(protoMethodName), ", request, ", factory, ", ", merged, ")")
		g.generated.P("}")
		g.generated.P()
	}
}

func (g fileGenerator) generateClientFromStreamMethods(clientName, serviceName, protoMethodName, methodName, contextType, inputType, outputType, factory, options, merged string) {
	requests := "requests " + g.runtime("MessageStream") + "[" + inputType + "]"
	g.generated.P("// ", methodName, "FromStream calls the ", protoMethodName, " RPC from an existing request stream.")
	g.generated.P("func (c *", clientName, ") ", methodName, "FromStream(ctx ", contextType, ", ", requests, ", ", options, ") (", outputType, ", error) {")
	g.generated.P("return ", g.runtime("ClientStreamingFromStream"), "[", inputType, ", ", outputType, "](ctx, c.transport, ", quoted(serviceName), ", ", quoted(protoMethodName), ", requests, ", factory, ", ", merged, ")")
	g.generated.P("}")
	g.generated.P()
	g.generated.P("// ", methodName, "FromStreamResponse calls the ", protoMethodName, " RPC and exposes response metadata.")
	g.generated.P("func (c *", clientName, ") ", methodName, "FromStreamResponse(ctx ", contextType, ", ", requests, ", ", options, ") (*", g.runtime("Response"), "[", outputType, "], error) {")
	g.generated.P("return ", g.runtime("ClientStreamingFromStreamResponse"), "[", inputType, ", ", outputType, "](ctx, c.transport, ", quoted(serviceName), ", ", quoted(protoMethodName), ", requests, ", factory, ", ", merged, ")")
	g.generated.P("}")
	g.generated.P()
}

func (g fileGenerator) generateBidiFromStreamMethods(clientName, serviceName, protoMethodName, methodName, contextType, inputType, outputType, factory, options, merged string) {
	requests := "requests " + g.runtime("MessageStream") + "[" + inputType + "]"
	g.generated.P("// ", methodName, "FromStream calls the ", protoMethodName, " RPC from an existing request stream.")
	g.generated.P("func (c *", clientName, ") ", methodName, "FromStream(ctx ", contextType, ", ", requests, ", ", options, ") (", g.runtime("MessageStream"), "[", outputType, "], error) {")
	g.generated.P("return ", g.runtime("BidirectionalStreamingFromStream"), "[", inputType, ", ", outputType, "](ctx, c.transport, ", quoted(serviceName), ", ", quoted(protoMethodName), ", requests, ", factory, ", ", merged, ")")
	g.generated.P("}")
	g.generated.P()
	g.generated.P("// ", methodName, "FromStreamResponse calls the ", protoMethodName, " RPC and exposes terminal metadata.")
	g.generated.P("func (c *", clientName, ") ", methodName, "FromStreamResponse(ctx ", contextType, ", ", requests, ", ", options, ") (", g.runtime("ResponseStream"), "[", outputType, "], error) {")
	g.generated.P("return ", g.runtime("BidirectionalStreamingFromStreamResponse"), "[", inputType, ", ", outputType, "](ctx, c.transport, ", quoted(serviceName), ", ", quoted(protoMethodName), ", requests, ", factory, ", ", merged, ")")
	g.generated.P("}")
	g.generated.P()
}

func (g fileGenerator) generateServerRegistration(serviceName string, method *protogen.Method) {
	inputType := g.messageType(method.Input)
	outputType := g.messageType(method.Output)
	factory := g.messageFactory(method.Input)
	var helper string
	switch {
	case method.Desc.IsStreamingClient() && method.Desc.IsStreamingServer():
		helper = g.runtime("RegisterBidirectionalStreamingResponse")
	case method.Desc.IsStreamingClient():
		helper = g.runtime("RegisterClientStreamingResponse")
	case method.Desc.IsStreamingServer():
		helper = g.runtime("RegisterServerStreamingResponse")
	default:
		helper = g.runtime("RegisterUnaryResponse")
	}
	g.generated.P(helper, "[", inputType, ", ", outputType, "](server, ", quoted(serviceName), ", ", quoted(string(method.Desc.Name())), ", ", factory, ", implementation.", method.GoName, ")")
}

func (g fileGenerator) serverRequestType(method *protogen.Method) string {
	if method.Desc.IsStreamingClient() {
		return g.runtime("MessageStream") + "[" + g.messageType(method.Input) + "]"
	}
	return g.messageType(method.Input)
}

func (g fileGenerator) serverResponseType(method *protogen.Method) string {
	outputType := g.messageType(method.Output)
	if method.Desc.IsStreamingServer() {
		return g.runtime("ResponseStream") + "[" + outputType + "]"
	}
	return "*" + g.runtime("Response") + "[" + outputType + "]"
}

func (g fileGenerator) messageType(message *protogen.Message) string {
	return "*" + g.qualified(message.GoIdent)
}

func (g fileGenerator) messageFactory(message *protogen.Message) string {
	typeName := g.qualified(message.GoIdent)
	return "func() *" + typeName + " { return &" + typeName + "{} }"
}

func (g fileGenerator) runtime(name string) string {
	return g.qualified(g.options.runtimeImport.Ident(name))
}

func (g fileGenerator) qualified(ident protogen.GoIdent) string {
	return g.generated.QualifiedGoIdent(ident)
}

func quoted(value string) string {
	return fmt.Sprintf("%q", value)
}
