package main

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"path"
	"sort"
	"strings"
	"unicode"

	"google.golang.org/protobuf/proto"
	descriptor "google.golang.org/protobuf/types/descriptorpb"
	plugin "google.golang.org/protobuf/types/pluginpb"
)

type pluginOptions struct {
	runtimeImport string
	fileSuffix    string
}

func defaultPluginOptions() pluginOptions {
	return pluginOptions{
		runtimeImport: "trev.zip/llc/trevrpc/trevrpc-go",
		fileSuffix:    ".trevrpc.go",
	}
}

type typeRef struct {
	protoName string
	goIdent   string
	goPackage string
	goImport  string
}

type typeIndex map[string]typeRef

func main() {
	if err := run(os.Stdin, os.Stdout); err != nil {
		fmt.Fprintf(os.Stderr, "protoc-gen-trevrpc-go: %v\n", err)
		os.Exit(1)
	}
}

func run(reader io.Reader, writer io.Writer) error {
	input, err := io.ReadAll(reader)
	if err != nil {
		return err
	}

	request := &plugin.CodeGeneratorRequest{}
	if err := proto.Unmarshal(input, request); err != nil {
		return fmt.Errorf("decode CodeGeneratorRequest: %w", err)
	}

	response := generate(request)
	output, err := proto.Marshal(response)
	if err != nil {
		return fmt.Errorf("encode CodeGeneratorResponse: %w", err)
	}

	_, err = writer.Write(output)
	return err
}

func generate(request *plugin.CodeGeneratorRequest) *plugin.CodeGeneratorResponse {
	options, err := parseOptions(request.GetParameter())
	if err != nil {
		return &plugin.CodeGeneratorResponse{Error: new(err.Error())}
	}

	filesToGenerate := map[string]bool{}
	for _, fileName := range request.FileToGenerate {
		filesToGenerate[fileName] = true
	}

	index := buildTypeIndex(request.ProtoFile)
	response := &plugin.CodeGeneratorResponse{}
	for _, file := range request.ProtoFile {
		if !filesToGenerate[file.GetName()] || len(file.Service) == 0 {
			continue
		}

		content, err := generateFile(file, request.ProtoFile, index, options)
		if err != nil {
			return &plugin.CodeGeneratorResponse{Error: new(err.Error())}
		}

		response.File = append(response.File, &plugin.CodeGeneratorResponse_File{
			Name:    new(outputFileName(file.GetName(), options.fileSuffix)),
			Content: new(content),
		})
	}

	return response
}

func parseOptions(parameter string) (pluginOptions, error) {
	options := defaultPluginOptions()
	if parameter == "" {
		return options, nil
	}

	for option := range strings.SplitSeq(parameter, ",") {
		if option == "" {
			continue
		}

		key, value, ok := strings.Cut(option, "=")
		if !ok {
			return options, fmt.Errorf("invalid trevrpc-go option %q; expected key=value", option)
		}

		switch key {
		case "runtime_import":
			options.runtimeImport = value
		case "file_suffix":
			options.fileSuffix = value
		default:
			return options, fmt.Errorf("unknown trevrpc-go option %q", key)
		}
	}

	return options, nil
}

func buildTypeIndex(files []*descriptor.FileDescriptorProto) typeIndex {
	index := typeIndex{}
	for _, file := range files {
		goPackage := fileGoPackageName(file)
		goImport := fileGoImportPath(file)
		for _, message := range file.MessageType {
			indexMessage(index, file.GetPackage(), nil, message, goPackage, goImport)
		}
	}

	return index
}

func indexMessage(index typeIndex, protoPackage string, parents []string, message *descriptor.DescriptorProto, goPackage, goImport string) {
	name := message.GetName()
	protoName := fullProtoName(protoPackage, append(parents, name))
	goParts := make([]string, 0, len(parents)+1)
	for _, parent := range parents {
		goParts = append(goParts, goExportedName(parent))
	}
	goParts = append(goParts, goExportedName(name))

	index[protoName] = typeRef{
		protoName: protoName,
		goIdent:   strings.Join(goParts, "_"),
		goPackage: goPackage,
		goImport:  goImport,
	}

	for _, nested := range message.NestedType {
		indexMessage(index, protoPackage, append(parents, name), nested, goPackage, goImport)
	}
}

func generateFile(file *descriptor.FileDescriptorProto, files []*descriptor.FileDescriptorProto, index typeIndex, options pluginOptions) (string, error) {
	goPackage := fileGoPackageName(file)
	imports := map[string]string{
		"context": "context",
		"trevrpc": options.runtimeImport,
	}

	services := make([]string, 0, len(file.Service))
	for _, service := range file.Service {
		serviceCode, err := generateService(file, service, index, imports)
		if err != nil {
			return "", err
		}

		services = append(services, serviceCode)
	}

	var buffer bytes.Buffer
	buffer.WriteString("// Code generated by protoc-gen-trevrpc-go. DO NOT EDIT.\n\n")
	buffer.WriteString("package ")
	buffer.WriteString(goPackage)
	buffer.WriteString("\n\n")
	writeImports(&buffer, imports)
	buffer.WriteString("func mergeTrevrpcCallOptions(base []trevrpc.CallOption, override []trevrpc.CallOption) []trevrpc.CallOption {\n")
	buffer.WriteString("\tif len(base) == 0 {\n")
	buffer.WriteString("\t\treturn override\n")
	buffer.WriteString("\t}\n")
	buffer.WriteString("\tif len(override) == 0 {\n")
	buffer.WriteString("\t\treturn base\n")
	buffer.WriteString("\t}\n")
	buffer.WriteString("\tmerged := make([]trevrpc.CallOption, 0, len(base)+len(override))\n")
	buffer.WriteString("\tmerged = append(merged, base...)\n")
	buffer.WriteString("\tmerged = append(merged, override...)\n")
	buffer.WriteString("\treturn merged\n")
	buffer.WriteString("}\n\n")

	for _, service := range services {
		buffer.WriteString(service)
		buffer.WriteByte('\n')
	}

	_ = files
	return buffer.String(), nil
}

func writeImports(buffer *bytes.Buffer, imports map[string]string) {
	aliases := make([]string, 0, len(imports))
	for alias := range imports {
		aliases = append(aliases, alias)
	}
	sort.Strings(aliases)

	buffer.WriteString("import (\n")
	for _, alias := range aliases {
		importPath := imports[alias]
		if alias == path.Base(importPath) || alias == "context" {
			fmt.Fprintf(buffer, "\t%q\n", importPath)
		} else {
			fmt.Fprintf(buffer, "\t%s %q\n", alias, importPath)
		}
	}
	buffer.WriteString(")\n\n")
}

func generateService(file *descriptor.FileDescriptorProto, service *descriptor.ServiceDescriptorProto, index typeIndex, imports map[string]string) (string, error) {
	serviceName := goExportedName(service.GetName())
	fullServiceName := service.GetName()
	if file.GetPackage() != "" {
		fullServiceName = file.GetPackage() + "." + service.GetName()
	}

	methods := make([]methodInfo, 0, len(service.Method))
	for _, method := range service.Method {
		methodInfo, err := describeMethod(file, method, index, imports)
		if err != nil {
			return "", err
		}

		methods = append(methods, methodInfo)
	}

	var buffer bytes.Buffer
	fmt.Fprintf(&buffer, "// %sServer handles the %s service.\n", serviceName, serviceName)
	fmt.Fprintf(&buffer, "type %sServer interface {\n", serviceName)
	for _, method := range methods {
		fmt.Fprintf(&buffer, "\t// %s handles the %s RPC.\n", method.name, method.protoName)
		fmt.Fprintf(&buffer, "\t%s\n", method.serverSignature)
	}
	buffer.WriteString("}\n\n")

	fmt.Fprintf(&buffer, "// %sClient calls the %s service.\n", serviceName, serviceName)
	fmt.Fprintf(&buffer, "type %sClient struct {\n", serviceName)
	buffer.WriteString("\ttransport trevrpc.Transport\n")
	buffer.WriteString("\toptions []trevrpc.CallOption\n")
	buffer.WriteString("}\n\n")
	fmt.Fprintf(&buffer, "// New%sClient creates a client for the %s service.\n", serviceName, serviceName)
	fmt.Fprintf(&buffer, "func New%sClient(transport trevrpc.Transport, options ...trevrpc.CallOption) *%sClient {\n", serviceName, serviceName)
	fmt.Fprintf(&buffer, "\treturn &%sClient{transport: transport, options: options}\n", serviceName)
	buffer.WriteString("}\n\n")

	for _, method := range methods {
		generateClientMethod(&buffer, serviceName, fullServiceName, method)
	}

	fmt.Fprintf(&buffer, "// Register%sServer registers handlers for the %s service.\n", serviceName, serviceName)
	fmt.Fprintf(&buffer, "func Register%sServer(server *trevrpc.Server, implementation %sServer) {\n", serviceName, serviceName)
	for _, method := range methods {
		generateServerRegistration(&buffer, fullServiceName, method)
	}
	buffer.WriteString("}\n")

	return buffer.String(), nil
}

type methodInfo struct {
	name            string
	protoName       string
	inputType       string
	outputType      string
	clientStreaming bool
	serverStreaming bool
	serverSignature string
}

func describeMethod(file *descriptor.FileDescriptorProto, method *descriptor.MethodDescriptorProto, index typeIndex, imports map[string]string) (methodInfo, error) {
	inputType, err := goTypeFor(file, method.GetInputType(), index, imports)
	if err != nil {
		return methodInfo{}, err
	}
	outputType, err := goTypeFor(file, method.GetOutputType(), index, imports)
	if err != nil {
		return methodInfo{}, err
	}

	info := methodInfo{
		name:            goExportedName(method.GetName()),
		protoName:       method.GetName(),
		inputType:       inputType,
		outputType:      outputType,
		clientStreaming: method.GetClientStreaming(),
		serverStreaming: method.GetServerStreaming(),
	}

	switch {
	case info.clientStreaming && info.serverStreaming:
		info.serverSignature = fmt.Sprintf("%s(context.Context, trevrpc.MessageStream[%s]) (trevrpc.MessageStream[%s], error)", info.name, inputType, outputType)
	case info.clientStreaming:
		info.serverSignature = fmt.Sprintf("%s(context.Context, trevrpc.MessageStream[%s]) (%s, error)", info.name, inputType, outputType)
	case info.serverStreaming:
		info.serverSignature = fmt.Sprintf("%s(context.Context, %s) (trevrpc.MessageStream[%s], error)", info.name, inputType, outputType)
	default:
		info.serverSignature = fmt.Sprintf("%s(context.Context, %s) (%s, error)", info.name, inputType, outputType)
	}

	return info, nil
}

func generateClientMethod(buffer *bytes.Buffer, serviceName, fullServiceName string, method methodInfo) {
	fmt.Fprintf(buffer, "// %s calls the %s RPC.\n", method.name, method.protoName)
	switch {
	case method.clientStreaming && method.serverStreaming:
		fmt.Fprintf(buffer, "func (c *%sClient) %s(ctx context.Context, options ...trevrpc.CallOption) (trevrpc.BidirectionalStreamingCall[%s, %s], error) {\n", serviceName, method.name, method.inputType, method.outputType)
		fmt.Fprintf(buffer, "\treturn trevrpc.BidirectionalStreaming[%s, %s](ctx, c.transport, %q, %q, func() %s { return &%s{} }, mergeTrevrpcCallOptions(c.options, options)...)\n", method.inputType, method.outputType, fullServiceName, method.protoName, method.outputType, strings.TrimPrefix(method.outputType, "*"))
		buffer.WriteString("}\n\n")
		fmt.Fprintf(buffer, "// %sFromStream calls the %s RPC from an existing request stream.\n", method.name, method.protoName)
		fmt.Fprintf(buffer, "func (c *%sClient) %sFromStream(ctx context.Context, requests trevrpc.MessageStream[%s], options ...trevrpc.CallOption) (trevrpc.MessageStream[%s], error) {\n", serviceName, method.name, method.inputType, method.outputType)
		fmt.Fprintf(buffer, "\treturn trevrpc.BidirectionalStreamingFromStream[%s, %s](ctx, c.transport, %q, %q, requests, func() %s { return &%s{} }, mergeTrevrpcCallOptions(c.options, options)...)\n", method.inputType, method.outputType, fullServiceName, method.protoName, method.outputType, strings.TrimPrefix(method.outputType, "*"))
	case method.clientStreaming:
		fmt.Fprintf(buffer, "func (c *%sClient) %s(ctx context.Context, options ...trevrpc.CallOption) (trevrpc.ClientStreamingCall[%s, %s], error) {\n", serviceName, method.name, method.inputType, method.outputType)
		fmt.Fprintf(buffer, "\treturn trevrpc.ClientStreaming[%s, %s](ctx, c.transport, %q, %q, func() %s { return &%s{} }, mergeTrevrpcCallOptions(c.options, options)...)\n", method.inputType, method.outputType, fullServiceName, method.protoName, method.outputType, strings.TrimPrefix(method.outputType, "*"))
		buffer.WriteString("}\n\n")
		fmt.Fprintf(buffer, "// %sFromStream calls the %s RPC from an existing request stream.\n", method.name, method.protoName)
		fmt.Fprintf(buffer, "func (c *%sClient) %sFromStream(ctx context.Context, requests trevrpc.MessageStream[%s], options ...trevrpc.CallOption) (%s, error) {\n", serviceName, method.name, method.inputType, method.outputType)
		fmt.Fprintf(buffer, "\treturn trevrpc.ClientStreamingFromStream[%s, %s](ctx, c.transport, %q, %q, requests, func() %s { return &%s{} }, mergeTrevrpcCallOptions(c.options, options)...)\n", method.inputType, method.outputType, fullServiceName, method.protoName, method.outputType, strings.TrimPrefix(method.outputType, "*"))
	case method.serverStreaming:
		fmt.Fprintf(buffer, "func (c *%sClient) %s(ctx context.Context, request %s, options ...trevrpc.CallOption) (trevrpc.MessageStream[%s], error) {\n", serviceName, method.name, method.inputType, method.outputType)
		fmt.Fprintf(buffer, "\treturn trevrpc.ServerStreaming[%s, %s](ctx, c.transport, %q, %q, request, func() %s { return &%s{} }, mergeTrevrpcCallOptions(c.options, options)...)\n", method.inputType, method.outputType, fullServiceName, method.protoName, method.outputType, strings.TrimPrefix(method.outputType, "*"))
		buffer.WriteString("}\n\n")
		fmt.Fprintf(buffer, "// %sResponse calls the %s RPC and returns a response stream with terminal metadata.\n", method.name, method.protoName)
		fmt.Fprintf(buffer, "func (c *%sClient) %sResponse(ctx context.Context, request %s, options ...trevrpc.CallOption) (trevrpc.ResponseStream[%s], error) {\n", serviceName, method.name, method.inputType, method.outputType)
		fmt.Fprintf(buffer, "\treturn trevrpc.ServerStreamingResponse[%s, %s](ctx, c.transport, %q, %q, request, func() %s { return &%s{} }, mergeTrevrpcCallOptions(c.options, options)...)\n", method.inputType, method.outputType, fullServiceName, method.protoName, method.outputType, strings.TrimPrefix(method.outputType, "*"))
	default:
		fmt.Fprintf(buffer, "func (c *%sClient) %s(ctx context.Context, request %s, options ...trevrpc.CallOption) (%s, error) {\n", serviceName, method.name, method.inputType, method.outputType)
		fmt.Fprintf(buffer, "\treturn trevrpc.Unary[%s, %s](ctx, c.transport, %q, %q, request, func() %s { return &%s{} }, mergeTrevrpcCallOptions(c.options, options)...)\n", method.inputType, method.outputType, fullServiceName, method.protoName, method.outputType, strings.TrimPrefix(method.outputType, "*"))
		buffer.WriteString("}\n\n")
		fmt.Fprintf(buffer, "// %sResponse calls the %s RPC and returns response metadata.\n", method.name, method.protoName)
		fmt.Fprintf(buffer, "func (c *%sClient) %sResponse(ctx context.Context, request %s, options ...trevrpc.CallOption) (*trevrpc.Response[%s], error) {\n", serviceName, method.name, method.inputType, method.outputType)
		fmt.Fprintf(buffer, "\treturn trevrpc.UnaryResponse[%s, %s](ctx, c.transport, %q, %q, request, func() %s { return &%s{} }, mergeTrevrpcCallOptions(c.options, options)...)\n", method.inputType, method.outputType, fullServiceName, method.protoName, method.outputType, strings.TrimPrefix(method.outputType, "*"))
	}
	buffer.WriteString("}\n\n")
}

func generateServerRegistration(buffer *bytes.Buffer, fullServiceName string, method methodInfo) {
	if !method.clientStreaming && !method.serverStreaming {
		fmt.Fprintf(buffer, "\tserver.Route(%q, %q, func(ctx context.Context, body []byte) ([]byte, error) {\n", fullServiceName, method.protoName)
		fmt.Fprintf(buffer, "\t\trequest := &%s{}\n", strings.TrimPrefix(method.inputType, "*"))
		buffer.WriteString("\t\tif err := trevrpc.UnmarshalMessage(body, request); err != nil {\n")
		buffer.WriteString("\t\t\treturn nil, trevrpc.InvalidArgument(\"failed to decode request: \"+err.Error())\n")
		buffer.WriteString("\t\t}\n")
		fmt.Fprintf(buffer, "\t\tresponse, err := implementation.%s(ctx, request)\n", method.name)
		buffer.WriteString("\t\tif err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
		buffer.WriteString("\t\tif response == nil {\n\t\t\treturn nil, trevrpc.Internal(\"handler returned nil response\")\n\t\t}\n")
		buffer.WriteString("\t\treturn trevrpc.MarshalMessage(response)\n")
		buffer.WriteString("\t})\n")
		return
	}

	kind := "trevrpc.RpcKindServerStreaming"
	if method.clientStreaming && method.serverStreaming {
		kind = "trevrpc.RpcKindBidirectionalStreaming"
	} else if method.clientStreaming {
		kind = "trevrpc.RpcKindClientStreaming"
	}

	fmt.Fprintf(buffer, "\tserver.RouteStreaming(%q, %q, %s, func(ctx context.Context, body []byte, requests trevrpc.ByteStream) (trevrpc.ByteStream, error) {\n", fullServiceName, method.protoName, kind)
	if method.clientStreaming {
		fmt.Fprintf(buffer, "\t\trequestStream := trevrpc.DecodeStream[%s](requests, func() %s { return &%s{} })\n", method.inputType, method.inputType, strings.TrimPrefix(method.inputType, "*"))
	} else {
		fmt.Fprintf(buffer, "\t\trequest := &%s{}\n", strings.TrimPrefix(method.inputType, "*"))
		buffer.WriteString("\t\tif err := trevrpc.UnmarshalMessage(body, request); err != nil {\n")
		buffer.WriteString("\t\t\treturn nil, trevrpc.InvalidArgument(\"failed to decode request: \"+err.Error())\n")
		buffer.WriteString("\t\t}\n")
	}

	switch {
	case method.clientStreaming && method.serverStreaming:
		fmt.Fprintf(buffer, "\t\tresponseStream, err := implementation.%s(ctx, requestStream)\n", method.name)
		buffer.WriteString("\t\tif err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
		fmt.Fprintf(buffer, "\t\treturn trevrpc.EncodeStream[%s](responseStream), nil\n", method.outputType)
	case method.clientStreaming:
		fmt.Fprintf(buffer, "\t\tresponse, err := implementation.%s(ctx, requestStream)\n", method.name)
		buffer.WriteString("\t\tif err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
		buffer.WriteString("\t\tif response == nil {\n\t\t\treturn nil, trevrpc.Internal(\"handler returned nil response\")\n\t\t}\n")
		buffer.WriteString("\t\treturn trevrpc.SingleMessageStream(response), nil\n")
	case method.serverStreaming:
		fmt.Fprintf(buffer, "\t\tresponseStream, err := implementation.%s(ctx, request)\n", method.name)
		buffer.WriteString("\t\tif err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
		fmt.Fprintf(buffer, "\t\treturn trevrpc.EncodeStream[%s](responseStream), nil\n", method.outputType)
	}
	buffer.WriteString("\t})\n")
}

func goTypeFor(file *descriptor.FileDescriptorProto, protoName string, index typeIndex, imports map[string]string) (string, error) {
	if !strings.HasPrefix(protoName, ".") {
		protoName = "." + file.GetPackage() + "." + protoName
	}

	typeRef, ok := index[protoName]
	if !ok {
		return "", fmt.Errorf("unknown protobuf message type %q", protoName)
	}

	currentImport := fileGoImportPath(file)
	currentPackage := fileGoPackageName(file)
	if typeRef.goImport == "" || typeRef.goImport == currentImport || typeRef.goPackage == currentPackage {
		return "*" + typeRef.goIdent, nil
	}

	alias := uniqueImportAlias(typeRef.goPackage, imports)
	imports[alias] = typeRef.goImport
	return "*" + alias + "." + typeRef.goIdent, nil
}

func uniqueImportAlias(base string, imports map[string]string) string {
	alias := sanitizeIdentifier(base)
	if alias == "" {
		alias = "protoimport"
	}
	if _, exists := imports[alias]; !exists {
		return alias
	}

	for i := 2; ; i++ {
		candidate := fmt.Sprintf("%s%d", alias, i)
		if _, exists := imports[candidate]; !exists {
			return candidate
		}
	}
}

func outputFileName(inputName, suffix string) string {
	ext := path.Ext(inputName)
	return strings.TrimSuffix(inputName, ext) + suffix
}

func fullProtoName(protoPackage string, names []string) string {
	parts := make([]string, 0, len(names)+1)
	if protoPackage != "" {
		parts = append(parts, protoPackage)
	}
	parts = append(parts, names...)
	return "." + strings.Join(parts, ".")
}

func fileGoPackageName(file *descriptor.FileDescriptorProto) string {
	goPackage := file.GetOptions().GetGoPackage()
	if _, name, ok := strings.Cut(goPackage, ";"); ok {
		return sanitizeIdentifier(name)
	}

	if goPackage != "" {
		base := path.Base(goPackage)
		if base != "." && base != "/" {
			return sanitizeIdentifier(base)
		}
	}

	if file.GetPackage() != "" {
		parts := strings.Split(file.GetPackage(), ".")
		return sanitizeIdentifier(parts[len(parts)-1])
	}

	return "proto"
}

func fileGoImportPath(file *descriptor.FileDescriptorProto) string {
	goPackage := file.GetOptions().GetGoPackage()
	if importPath, _, ok := strings.Cut(goPackage, ";"); ok {
		return importPath
	}

	if strings.Contains(goPackage, "/") {
		return goPackage
	}

	return ""
}

func goExportedName(name string) string {
	if name == "" {
		return "X"
	}

	parts := strings.FieldsFunc(name, func(r rune) bool {
		return r == '_' || r == '-' || r == '.'
	})
	for i, part := range parts {
		if part == "" {
			continue
		}

		runes := []rune(part)
		runes[0] = unicode.ToUpper(runes[0])
		parts[i] = string(runes)
	}

	return strings.Join(parts, "")
}

func sanitizeIdentifier(name string) string {
	if name == "" {
		return ""
	}

	var builder strings.Builder
	for i, r := range name {
		if r == '_' || unicode.IsLetter(r) || (i > 0 && unicode.IsDigit(r)) {
			builder.WriteRune(r)
		}
	}

	result := builder.String()
	if result == "" {
		return "_"
	}

	if unicode.IsDigit([]rune(result)[0]) {
		return "_" + result
	}

	return result
}
