// Code generated by protoc-gen-trevrpc-js. DO NOT EDIT.

import { registerTypedService } from "../../src/node-generated.js";
import { GreeterService, root } from "./greeter.trevrpc.js";

/** Registers typed Node handlers for the Greeter service. */
export function registerGreeterServer(server, handlers) {
  return registerTypedService(server, root, GreeterService, handlers);
}
