// Code generated by protoc-gen-trevrpc-js. DO NOT EDIT.

import type {
  NodeServer,
  NodeServerCall,
  StreamingServerResponse,
  UnaryServerResponse,
} from "../../src/node-generated.js";
import type { HelloRequest, HelloReply } from "./greeter.trevrpc.js";

/** Typed Node handlers for the Greeter service. */
export interface GreeterHandlers {
  sayHello?(
    request: HelloRequest,
    call: NodeServerCall,
  ):
    | HelloReply
    | UnaryServerResponse<HelloReply>
    | Promise<HelloReply | UnaryServerResponse<HelloReply>>;
  lotsOfReplies?(
    request: HelloRequest,
    call: NodeServerCall,
  ):
    | Iterable<HelloReply>
    | AsyncIterable<HelloReply>
    | StreamingServerResponse<HelloReply>
    | Promise<
        Iterable<HelloReply> | AsyncIterable<HelloReply> | StreamingServerResponse<HelloReply>
      >;
  lotsOfGreetings?(
    requests: AsyncIterable<HelloRequest>,
    call: NodeServerCall,
  ):
    | HelloReply
    | UnaryServerResponse<HelloReply>
    | Promise<HelloReply | UnaryServerResponse<HelloReply>>;
  bidiHello?(
    requests: AsyncIterable<HelloRequest>,
    call: NodeServerCall,
  ):
    | Iterable<HelloReply>
    | AsyncIterable<HelloReply>
    | StreamingServerResponse<HelloReply>
    | Promise<
        Iterable<HelloReply> | AsyncIterable<HelloReply> | StreamingServerResponse<HelloReply>
      >;
}

/** Registers typed Node handlers for the Greeter service. */
export declare function registerGreeterServer(
  server: NodeServer,
  handlers: GreeterHandlers,
): NodeServer;
