// Code generated by protoc-gen-trevrpc-js. DO NOT EDIT.

import { createRoot, createServiceClient } from "../../src/index.js";

export const root = createRoot({
  nested: {
    example: {
      nested: {
        greeter: {
          nested: {
            HelloRequest: {
              fields: {
                name: {
                  type: "string",
                  id: 1,
                },
              },
            },
            HelloReply: {
              fields: {
                message: {
                  type: "string",
                  id: 1,
                },
              },
            },
          },
        },
      },
    },
  },
});

/** Service descriptor for the Greeter service. */
export const GreeterService = Object.freeze({
  name: "Greeter",
  fullName: "example.greeter.Greeter",
  exportName: "GreeterService",
  methods: {
    sayHello: {
      name: "SayHello",
      kind: "unary",
      inputType: "example.greeter.HelloRequest",
      outputType: "example.greeter.HelloReply",
    },
    lotsOfReplies: {
      name: "LotsOfReplies",
      kind: "serverStreaming",
      inputType: "example.greeter.HelloRequest",
      outputType: "example.greeter.HelloReply",
    },
    lotsOfGreetings: {
      name: "LotsOfGreetings",
      kind: "clientStreaming",
      inputType: "example.greeter.HelloRequest",
      outputType: "example.greeter.HelloReply",
    },
    bidiHello: {
      name: "BidiHello",
      kind: "bidirectionalStreaming",
      inputType: "example.greeter.HelloRequest",
      outputType: "example.greeter.HelloReply",
    },
  },
});

/** Client for the Greeter service. */
export class GreeterClient {
  /** Creates a client for the Greeter service. */
  constructor(transport, options = {}) {
    this._client = createServiceClient(transport, GreeterService, root, options);
  }

  /** Calls the SayHello RPC. */
  sayHello(request, options = {}) {
    return this._client.sayHello(request, options);
  }

  /** Calls the LotsOfReplies RPC. */
  lotsOfReplies(request, options = {}) {
    return this._client.lotsOfReplies(request, options);
  }

  /** Calls the LotsOfGreetings RPC. */
  lotsOfGreetings(options = {}) {
    return this._client.lotsOfGreetings(options);
  }

  /** Calls the BidiHello RPC. */
  bidiHello(options = {}) {
    return this._client.bidiHello(options);
  }
}

/** Creates a client for the Greeter service. */
export function createGreeterClient(transport, options = {}) {
  return new GreeterClient(transport, options);
}
