// Code generated by protoc-gen-trevrpc-js. DO NOT EDIT.

import type { Root } from "protobufjs";

import type { CallOptions, RpcServiceDescriptor, Transport } from "../../src/index.js";

export declare const root: Root;

export interface HelloRequest {
  name?: string;
}

export interface HelloReply {
  message?: string;
}

/** Service descriptor for the Greeter service. */
export declare const GreeterService: RpcServiceDescriptor;

/** Client for the Greeter service. */
export declare class GreeterClient {
  /** Creates a client for the Greeter service. */
  constructor(transport: Transport, options?: CallOptions);

  /** Calls the SayHello RPC. */
  sayHello(request: HelloRequest, options?: CallOptions): Promise<HelloReply>;
  /** Calls the LotsOfReplies RPC. */
  lotsOfReplies(request: HelloRequest, options?: CallOptions): Promise<AsyncIterable<HelloReply>>;
  /** Calls the LotsOfGreetings RPC. */
  lotsOfGreetings(
    requests: AsyncIterable<HelloRequest>,
    options?: CallOptions,
  ): Promise<HelloReply>;
  /** Calls the BidiHello RPC. */
  bidiHello(
    requests: AsyncIterable<HelloRequest>,
    options?: CallOptions,
  ): Promise<AsyncIterable<HelloReply>>;
}

/** Creates a client for the Greeter service. */
export declare function createGreeterClient(
  transport: Transport,
  options?: CallOptions,
): GreeterClient;
