// Code generated by protoc-gen-trevrpc-js. DO NOT EDIT.

import type { Root } from "protobufjs";

import type { CallOptions, RpcServiceDescriptor, Transport } from "../../src/index.js";

export declare const root: Root;

export interface HelloRequest {
  name?: string;
}

export interface HelloReply {
  message?: string;
}

export declare const GreeterService: RpcServiceDescriptor;

export declare class GreeterClient {
  constructor(transport: Transport, options?: CallOptions);

  sayHello(request: HelloRequest, options?: CallOptions): Promise<HelloReply>;
  lotsOfReplies(request: HelloRequest, options?: CallOptions): Promise<AsyncIterable<HelloReply>>;
  lotsOfGreetings(
    requests: AsyncIterable<HelloRequest>,
    options?: CallOptions,
  ): Promise<HelloReply>;
  bidiHello(
    requests: AsyncIterable<HelloRequest>,
    options?: CallOptions,
  ): Promise<AsyncIterable<HelloReply>>;
}

export declare function createGreeterClient(
  transport: Transport,
  options?: CallOptions,
): GreeterClient;
