// Code generated by protoc-gen-trevrpc-js. DO NOT EDIT.

import type { Long, Root } from "protobufjs";

import type {
  BidirectionalStreamingCall,
  CallOptions,
  ClientStreamingCall,
  ResponseAsyncIterable,
  RpcServiceDescriptor,
  Transport,
  UnaryResponse,
} from "../../src/index.js";

export declare const root: Root;

export interface HelloRequest {
  name?: string;
}

export interface HelloReply {
  message?: string;
}

/** Service descriptor for the Greeter service. */
export declare const GreeterService: RpcServiceDescriptor;

/** Client for the Greeter service. */
export declare class GreeterClient {
  /** Creates a client for the Greeter service. */
  constructor(transport: Transport, options?: CallOptions);

  /** Calls the SayHello RPC. */
  sayHello(request: HelloRequest, options?: CallOptions): Promise<HelloReply>;
  /** Calls the SayHello RPC and returns response metadata. */
  sayHelloWithResponse(
    request: HelloRequest,
    options?: CallOptions,
  ): Promise<UnaryResponse<HelloReply>>;
  /** Calls the LotsOfReplies RPC. */
  lotsOfReplies(
    request: HelloRequest,
    options?: CallOptions,
  ): Promise<ResponseAsyncIterable<HelloReply>>;
  /** Calls the LotsOfGreetings RPC. */
  lotsOfGreetings(options?: CallOptions): Promise<ClientStreamingCall<HelloRequest, HelloReply>>;
  /** Calls the BidiHello RPC. */
  bidiHello(options?: CallOptions): Promise<BidirectionalStreamingCall<HelloRequest, HelloReply>>;
}

/** Creates a client for the Greeter service. */
export declare function createGreeterClient(
  transport: Transport,
  options?: CallOptions,
): GreeterClient;
