[versions]
bouncycastle = "1.85"
coroutines = "1.11.0"
cronet = "143.7445.0"
junit = "6.1.2"
kotlin = "2.4.0"
netty = "4.2.16.Final"
protobuf = "4.35.1"
protobuf-plugin = "0.10.0"

[libraries]
bouncycastle-bcpkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncycastle" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
cronet-api = { module = "org.chromium.net:cronet-api", version.ref = "cronet" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
netty-bom = { module = "io.netty:netty-bom", version.ref = "netty" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }
