name: check

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

permissions:
  contents: read

jobs:
  check:
    if: ${{ !startsWith(github.event.head_commit.message || github.event.pull_request.title || '', 'bump:') }}
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@3111d9c56193a4983beca8b41a2e0835678abcaa # v1.63.0

      - name: Check
        run: nix flake check --option log-lines 100

  webkit-macos:
    if: ${{ !startsWith(github.event.head_commit.message || github.event.pull_request.title || '', 'bump:') }}
    runs-on: macos-26
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@3111d9c56193a4983beca8b41a2e0835678abcaa # v1.63.0

      - name: Check Kotlin
        run: nix build .#checks.aarch64-darwin.kotlin --no-link --option log-lines 100

      - name: Check WebKit
        run: |
          nix build --impure --expr '
            let
              flake = builtins.getFlake (toString ./.);
            in
            flake.checks.aarch64-darwin.benchmark-webkit-smoke.overrideAttrs (_: {
              TREVRPC_BENCH_RUN_ENTIRE_CAMPAIGN = "true";
            })
          ' --no-link --option log-lines 100
