name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: release

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@3111d9c56193a4983beca8b41a2e0835678abcaa # v1.63.0

      - name: Check
        run: nix flake check

  github:
    needs: check
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@3111d9c56193a4983beca8b41a2e0835678abcaa # v1.63.0
        with:
          fetch_depth: 0
          shell: release

      - name: Release to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGES: |
            packages.x86_64-linux.trevrpc-go.x86_64-unknown-linux-musl
            packages.x86_64-linux.trevrpc-rust.x86_64-unknown-linux-musl
        run: flake-release
