name: release

on:
  push:
    tags: ["**"]
  workflow_dispatch:

concurrency:
  group: release

permissions:
  contents: read

jobs:
  check:
    if: >-
      startsWith(github.ref, 'refs/tags/trevrpc-go/v') ||
      startsWith(github.ref, 'refs/tags/trevrpc-rust/v')
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@c7537bc73ce11ca01e53bd9d119d6e46363f9888 # v1.65.0

      - name: Check
        run: nix flake check

  github:
    if: >-
      startsWith(github.ref, 'refs/tags/trevrpc-go/v') ||
      startsWith(github.ref, 'refs/tags/trevrpc-rust/v')
    needs: check
    name: github
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@c7537bc73ce11ca01e53bd9d119d6e46363f9888 # v1.65.0
        with:
          fetch_depth: 0
          shell: release

      - name: Release package to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          package="${GITHUB_REF_NAME%%/*}"
          .forgejo/scripts/release-nix-package.sh "$package"
