[package]
name = "trevrpc-conformance-rust"
version = "0.1.10"
edition = "2024"
rust-version = "1.95.0"
publish = false

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
module_name_repetitions = "allow"

[dependencies]
prost = "0.14.4"
serde_json = "1.0.150"
trevrpc = { path = "../..", default-features = false }

[[bin]]
name = "trevrpc-conformance-rust"
path = "src/main.rs"
